/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.gotransverse.svs.webhook.client.http.client.HttpContext;

public class ErrorException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 4808931556105009207L;
    private String code;
    private String message;
    /** GETTER
     * A code for the specific error.  Used to help in determining possible root causes of an error.
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * A code for the specific error.  Used to help in determining possible root causes of an error.
     */
    @JsonSetter("code")
    private void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * A message providing additional detail for an error.
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * A message providing additional detail for an error.
     */
    @JsonSetter("message")
    private void setMessage (String value) { 
        this.message = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ErrorException(String reason, HttpContext context) {
        super(reason, context);
    }
}
 