/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;

public class ExportRegisterBalanceBySourceBuilder {
    //the instance to build
    private ExportRegisterBalanceBySource exportRegisterBalanceBySource;

    /**
     * Default constructor to initialize the instance
     */
    public ExportRegisterBalanceBySourceBuilder() {
        exportRegisterBalanceBySource = new ExportRegisterBalanceBySource();
    }

    /**
     * A unique identifier for this record.
     */
    public ExportRegisterBalanceBySourceBuilder uuid(String uuid) {
        exportRegisterBalanceBySource.setUuid(uuid);
        return this;
    }

    /**
     * The internal register id for the register.
     */
    public ExportRegisterBalanceBySourceBuilder registerId(Long registerId) {
        exportRegisterBalanceBySource.setRegisterId(registerId);
        return this;
    }

    /**
     * The register type per the initial register setup.
     */
    public ExportRegisterBalanceBySourceBuilder registerType(String registerType) {
        exportRegisterBalanceBySource.setRegisterType(registerType);
        return this;
    }

    /**
     * The currency code based upon ISO 4217
     */
    public ExportRegisterBalanceBySourceBuilder registerCurrency(CurrencyEnum registerCurrency) {
        exportRegisterBalanceBySource.setRegisterCurrency(registerCurrency);
        return this;
    }

    /**
     * The register's unit of measure
     */
    public ExportRegisterBalanceBySourceBuilder registerUom(String registerUom) {
        exportRegisterBalanceBySource.setRegisterUom(registerUom);
        return this;
    }

    /**
     * The register's external account id.
     */
    public ExportRegisterBalanceBySourceBuilder registerAccountId(Long registerAccountId) {
        exportRegisterBalanceBySource.setRegisterAccountId(registerAccountId);
        return this;
    }

    /**
     * The register's external account number.
     */
    public ExportRegisterBalanceBySourceBuilder registerAccountNumber(String registerAccountNumber) {
        exportRegisterBalanceBySource.setRegisterAccountNumber(registerAccountNumber);
        return this;
    }

    /**
     * The category of the register associated with this balance
     */
    public ExportRegisterBalanceBySourceBuilder registerCategory(String registerCategory) {
        exportRegisterBalanceBySource.setRegisterCategory(registerCategory);
        return this;
    }

    /**
     * The service_id that is consuming from the balance.
     */
    public ExportRegisterBalanceBySourceBuilder sourceId(String sourceId) {
        exportRegisterBalanceBySource.setSourceId(sourceId);
        return this;
    }

    /**
     * The type of transaction consuming from the balance.
     */
    public ExportRegisterBalanceBySourceBuilder sourceType(String sourceType) {
        exportRegisterBalanceBySource.setSourceType(sourceType);
        return this;
    }

    /**
     * The category of the transaction consuming from the balance.
     */
    public ExportRegisterBalanceBySourceBuilder sourceCategory(String sourceCategory) {
        exportRegisterBalanceBySource.setSourceCategory(sourceCategory);
        return this;
    }

    /**
     * The total amount of the balance on the register
     */
    public ExportRegisterBalanceBySourceBuilder balanceAmount(Double balanceAmount) {
        exportRegisterBalanceBySource.setBalanceAmount(balanceAmount);
        return this;
    }

    /**
     * The total number of transactions on the register
     */
    public ExportRegisterBalanceBySourceBuilder balanceCount(Integer balanceCount) {
        exportRegisterBalanceBySource.setBalanceCount(balanceCount);
        return this;
    }

    /**
     * The total amount of the consumption balance on the register
     */
    public ExportRegisterBalanceBySourceBuilder consumptionBalanceAmount(Double consumptionBalanceAmount) {
        exportRegisterBalanceBySource.setConsumptionBalanceAmount(consumptionBalanceAmount);
        return this;
    }

    /**
     * The total number of consumption transactions on the register
     */
    public ExportRegisterBalanceBySourceBuilder consumptionBalanceCount(Integer consumptionBalanceCount) {
        exportRegisterBalanceBySource.setConsumptionBalanceCount(consumptionBalanceCount);
        return this;
    }

    /**
     * The total amount of the contribution balance on the register
     */
    public ExportRegisterBalanceBySourceBuilder contributionBalanceAmount(Double contributionBalanceAmount) {
        exportRegisterBalanceBySource.setContributionBalanceAmount(contributionBalanceAmount);
        return this;
    }

    /**
     * The total number of contribution transactions on the register
     */
    public ExportRegisterBalanceBySourceBuilder contributionBalanceCount(Integer contributionBalanceCount) {
        exportRegisterBalanceBySource.setContributionBalanceCount(contributionBalanceCount);
        return this;
    }

    /**
     * The total amount of unallocated consumption on the register
     */
    public ExportRegisterBalanceBySourceBuilder unallocatedConsumptionBalanceAmount(Double unallocatedConsumptionBalanceAmount) {
        exportRegisterBalanceBySource.setUnallocatedConsumptionBalanceAmount(unallocatedConsumptionBalanceAmount);
        return this;
    }

    /**
     * The unallocated date based upon the business entity's timezone in YYYY-MM-DD format.
     */
    public ExportRegisterBalanceBySourceBuilder asOfDate(Date asOfDate) {
        exportRegisterBalanceBySource.setAsOfDate(asOfDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportRegisterBalanceBySource build() {
        return exportRegisterBalanceBySource;
    }
}