/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum GrantedUnitOfMeasureEnum {
    MONEY, //TODO: Write general description for this element
    POINTS, //TODO: Write general description for this element
    COUNT; //TODO: Write general description for this element

    private static TreeMap<String, GrantedUnitOfMeasureEnum> valueMap = new TreeMap<String, GrantedUnitOfMeasureEnum>();
    private String value;

    static {
        MONEY.value = "MONEY";
        POINTS.value = "POINTS";
        COUNT.value = "COUNT";

        valueMap.put("MONEY", MONEY);
        valueMap.put("POINTS", POINTS);
        valueMap.put("COUNT", COUNT);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static GrantedUnitOfMeasureEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of GrantedUnitOfMeasureEnum values to list of string values
     * @param toConvert The list of GrantedUnitOfMeasureEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<GrantedUnitOfMeasureEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (GrantedUnitOfMeasureEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 