/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;

public class StoredValueConsumptionBuilder {
    //the instance to build
    private StoredValueConsumption storedValueConsumption;

    /**
     * Default constructor to initialize the instance
     */
    public StoredValueConsumptionBuilder() {
        storedValueConsumption = new StoredValueConsumption();
    }

    /**
     * The granted value of contribution.  Draw downs occur off of this value.  Can be negative.
     */
    public StoredValueConsumptionBuilder consumedValue(Double consumedValue) {
        storedValueConsumption.setConsumedValue(consumedValue);
        return this;
    }

    /**
     * A source id for this transaction.
     */
    public StoredValueConsumptionBuilder sourceId(String sourceId) {
        storedValueConsumption.setSourceId(sourceId);
        return this;
    }

    /**
     * The type of record that this source correpsonds to.
     */
    public StoredValueConsumptionBuilder sourceType(String sourceType) {
        storedValueConsumption.setSourceType(sourceType);
        return this;
    }

    /**
     * A source description for this transaction.
     */
    public StoredValueConsumptionBuilder sourceDescription(String sourceDescription) {
        storedValueConsumption.setSourceDescription(sourceDescription);
        return this;
    }

    /**
     * A source category for this transaction.
     */
    public StoredValueConsumptionBuilder sourceCategory(String sourceCategory) {
        storedValueConsumption.setSourceCategory(sourceCategory);
        return this;
    }

    /**
     * The date this transaction is effective.  Can be in the past.
     */
    public StoredValueConsumptionBuilder effectiveDate(Date effectiveDate) {
        storedValueConsumption.setEffectiveDate(effectiveDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StoredValueConsumption build() {
        return storedValueConsumption;
    }
}