/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;

public class StoreDateRangeBuilder {
    //the instance to build
    private StoreDateRange storeDateRange;

    /**
     * Default constructor to initialize the instance
     */
    public StoreDateRangeBuilder() {
        storeDateRange = new StoreDateRange();
    }

    public StoreDateRangeBuilder minTransactionDate(Date minTransactionDate) {
        storeDateRange.setMinTransactionDate(minTransactionDate);
        return this;
    }

    public StoreDateRangeBuilder maxTransactionDate(Date maxTransactionDate) {
        storeDateRange.setMaxTransactionDate(maxTransactionDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StoreDateRange build() {
        return storeDateRange;
    }
}