/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StoredValueConsumption 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5624197900739394759L;
    private Double consumedValue;
    private String sourceId;
    private String sourceType;
    private String sourceDescription;
    private String sourceCategory;
    private Date effectiveDate;
    /** GETTER
     * The granted value of contribution.  Draw downs occur off of this value.  Can be negative.
     */
    @JsonGetter("consumed_value")
    public Double getConsumedValue ( ) { 
        return this.consumedValue;
    }
    
    /** SETTER
     * The granted value of contribution.  Draw downs occur off of this value.  Can be negative.
     */
    @JsonSetter("consumed_value")
    public void setConsumedValue (Double value) { 
        this.consumedValue = value;
    }
 
    /** GETTER
     * A source id for this transaction.
     */
    @JsonGetter("source_id")
    public String getSourceId ( ) { 
        return this.sourceId;
    }
    
    /** SETTER
     * A source id for this transaction.
     */
    @JsonSetter("source_id")
    public void setSourceId (String value) { 
        this.sourceId = value;
    }
 
    /** GETTER
     * The type of record that this source correpsonds to.
     */
    @JsonGetter("source_type")
    public String getSourceType ( ) { 
        return this.sourceType;
    }
    
    /** SETTER
     * The type of record that this source correpsonds to.
     */
    @JsonSetter("source_type")
    public void setSourceType (String value) { 
        this.sourceType = value;
    }
 
    /** GETTER
     * A source description for this transaction.
     */
    @JsonGetter("source_description")
    public String getSourceDescription ( ) { 
        return this.sourceDescription;
    }
    
    /** SETTER
     * A source description for this transaction.
     */
    @JsonSetter("source_description")
    public void setSourceDescription (String value) { 
        this.sourceDescription = value;
    }
 
    /** GETTER
     * A source category for this transaction.
     */
    @JsonGetter("source_category")
    public String getSourceCategory ( ) { 
        return this.sourceCategory;
    }
    
    /** SETTER
     * A source category for this transaction.
     */
    @JsonSetter("source_category")
    public void setSourceCategory (String value) { 
        this.sourceCategory = value;
    }
 
    /** GETTER
     * The date this transaction is effective.  Can be in the past.
     */
    @JsonGetter("effective_date")
    public Date getEffectiveDate ( ) { 
        return this.effectiveDate;
    }
    
    /** SETTER
     * The date this transaction is effective.  Can be in the past.
     */
    @JsonSetter("effective_date")
    public void setEffectiveDate (Date value) { 
        this.effectiveDate = value;
    }
 
}
 