/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StoreDateRange 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5699499161199963380L;
    private Date minTransactionDate;
    private Date maxTransactionDate;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("min_transaction_date")
    public Date getMinTransactionDate ( ) { 
        return this.minTransactionDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("min_transaction_date")
    public void setMinTransactionDate (Date value) { 
        this.minTransactionDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("max_transaction_date")
    public Date getMaxTransactionDate ( ) { 
        return this.maxTransactionDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("max_transaction_date")
    public void setMaxTransactionDate (Date value) { 
        this.maxTransactionDate = value;
    }
 
}
 