/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;

public class StoredValueTransactionBuilder {
    //the instance to build
    private StoredValueTransaction storedValueTransaction;

    /**
     * Default constructor to initialize the instance
     */
    public StoredValueTransactionBuilder() {
        storedValueTransaction = new StoredValueTransaction();
    }

    /**
     * The value of contribution or drawdown.
     */
    public StoredValueTransactionBuilder amount(Double amount) {
        storedValueTransaction.setAmount(amount);
        return this;
    }

    /**
     * The weighed amount of the consumption based off of the ordered amount.  Based up a "traunched draw-down" of the contributions.
     */
    public StoredValueTransactionBuilder weightedConsumptionOrderAmount(Double weightedConsumptionOrderAmount) {
        storedValueTransaction.setWeightedConsumptionOrderAmount(weightedConsumptionOrderAmount);
        return this;
    }

    /**
     * The weighed amount of the consumption based off of the list amount.  Based up a "traunched draw-down" of the contributions.
     */
    public StoredValueTransactionBuilder weightedConsumptionListAmount(Double weightedConsumptionListAmount) {
        storedValueTransaction.setWeightedConsumptionListAmount(weightedConsumptionListAmount);
        return this;
    }

    public StoredValueTransactionBuilder direction(DirectionEnum direction) {
        storedValueTransaction.setDirection(direction);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StoredValueTransaction build() {
        return storedValueTransaction;
    }
}