/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StoredValueTransaction 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5130189278312289423L;
    private Double amount;
    private Double weightedConsumptionOrderAmount;
    private Double weightedConsumptionListAmount;
    private DirectionEnum direction;
    /** GETTER
     * The value of contribution or drawdown.
     */
    @JsonGetter("amount")
    public Double getAmount ( ) { 
        return this.amount;
    }
    
    /** SETTER
     * The value of contribution or drawdown.
     */
    @JsonSetter("amount")
    public void setAmount (Double value) { 
        this.amount = value;
    }
 
    /** GETTER
     * The weighed amount of the consumption based off of the ordered amount.  Based up a "traunched draw-down" of the contributions.
     */
    @JsonGetter("weighted_consumption_order_amount")
    public Double getWeightedConsumptionOrderAmount ( ) { 
        return this.weightedConsumptionOrderAmount;
    }
    
    /** SETTER
     * The weighed amount of the consumption based off of the ordered amount.  Based up a "traunched draw-down" of the contributions.
     */
    @JsonSetter("weighted_consumption_order_amount")
    public void setWeightedConsumptionOrderAmount (Double value) { 
        this.weightedConsumptionOrderAmount = value;
    }
 
    /** GETTER
     * The weighed amount of the consumption based off of the list amount.  Based up a "traunched draw-down" of the contributions.
     */
    @JsonGetter("weighted_consumption_list_amount")
    public Double getWeightedConsumptionListAmount ( ) { 
        return this.weightedConsumptionListAmount;
    }
    
    /** SETTER
     * The weighed amount of the consumption based off of the list amount.  Based up a "traunched draw-down" of the contributions.
     */
    @JsonSetter("weighted_consumption_list_amount")
    public void setWeightedConsumptionListAmount (Double value) { 
        this.weightedConsumptionListAmount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("direction")
    public DirectionEnum getDirection ( ) { 
        return this.direction;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("direction")
    public void setDirection (DirectionEnum value) { 
        this.direction = value;
    }
 
}
 