/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum TimezoneEnum {
    ENUM_AFRICA/ABIDJAN, //TODO: Write general description for this element
    ENUM_AFRICA/ACCRA, //TODO: Write general description for this element
    ENUM_AFRICA/ADDIS_ABABA, //TODO: Write general description for this element
    ENUM_AFRICA/ALGIERS, //TODO: Write general description for this element
    ENUM_AFRICA/ASMARA, //TODO: Write general description for this element
    ENUM_AFRICA/BAMAKO, //TODO: Write general description for this element
    ENUM_AFRICA/BANGUI, //TODO: Write general description for this element
    ENUM_AFRICA/BANJUL, //TODO: Write general description for this element
    ENUM_AFRICA/BISSAU, //TODO: Write general description for this element
    ENUM_AFRICA/BLANTYRE, //TODO: Write general description for this element
    ENUM_AFRICA/BRAZZAVILLE, //TODO: Write general description for this element
    ENUM_AFRICA/BUJUMBURA, //TODO: Write general description for this element
    ENUM_AFRICA/CAIRO, //TODO: Write general description for this element
    ENUM_AFRICA/CASABLANCA, //TODO: Write general description for this element
    ENUM_AFRICA/CEUTA, //TODO: Write general description for this element
    ENUM_AFRICA/CONAKRY, //TODO: Write general description for this element
    ENUM_AFRICA/DAKAR, //TODO: Write general description for this element
    ENUM_AFRICA/DAR_ES_SALAAM, //TODO: Write general description for this element
    ENUM_AFRICA/DJIBOUTI, //TODO: Write general description for this element
    ENUM_AFRICA/DOUALA, //TODO: Write general description for this element
    ENUM_AFRICA/EL_AAIUN, //TODO: Write general description for this element
    ENUM_AFRICA/FREETOWN, //TODO: Write general description for this element
    ENUM_AFRICA/GABORONE, //TODO: Write general description for this element
    ENUM_AFRICA/HARARE, //TODO: Write general description for this element
    ENUM_AFRICA/JOHANNESBURG, //TODO: Write general description for this element
    ENUM_AFRICA/JUBA, //TODO: Write general description for this element
    ENUM_AFRICA/KAMPALA, //TODO: Write general description for this element
    ENUM_AFRICA/KHARTOUM, //TODO: Write general description for this element
    ENUM_AFRICA/KIGALI, //TODO: Write general description for this element
    ENUM_AFRICA/KINSHASA, //TODO: Write general description for this element
    ENUM_AFRICA/LAGOS, //TODO: Write general description for this element
    ENUM_AFRICA/LIBREVILLE, //TODO: Write general description for this element
    ENUM_AFRICA/LOME, //TODO: Write general description for this element
    ENUM_AFRICA/LUANDA, //TODO: Write general description for this element
    ENUM_AFRICA/LUBUMBASHI, //TODO: Write general description for this element
    ENUM_AFRICA/LUSAKA, //TODO: Write general description for this element
    ENUM_AFRICA/MALABO, //TODO: Write general description for this element
    ENUM_AFRICA/MAPUTO, //TODO: Write general description for this element
    ENUM_AFRICA/MASERU, //TODO: Write general description for this element
    ENUM_AFRICA/MBABANE, //TODO: Write general description for this element
    ENUM_AFRICA/MOGADISHU, //TODO: Write general description for this element
    ENUM_AFRICA/MONROVIA, //TODO: Write general description for this element
    ENUM_AFRICA/NAIROBI, //TODO: Write general description for this element
    ENUM_AFRICA/NDJAMENA, //TODO: Write general description for this element
    ENUM_AFRICA/NIAMEY, //TODO: Write general description for this element
    ENUM_AFRICA/NOUAKCHOTT, //TODO: Write general description for this element
    ENUM_AFRICA/OUAGADOUGOU, //TODO: Write general description for this element
    ENUM_AFRICA/PORTO-NOVO, //TODO: Write general description for this element
    ENUM_AFRICA/SAO_TOME, //TODO: Write general description for this element
    ENUM_AFRICA/TRIPOLI, //TODO: Write general description for this element
    ENUM_AFRICA/TUNIS, //TODO: Write general description for this element
    ENUM_AFRICA/WINDHOEK, //TODO: Write general description for this element
    ENUM_AMERICA/ADAK, //TODO: Write general description for this element
    ENUM_AMERICA/ANCHORAGE, //TODO: Write general description for this element
    ENUM_AMERICA/ANGUILLA, //TODO: Write general description for this element
    ENUM_AMERICA/ANTIGUA, //TODO: Write general description for this element
    ENUM_AMERICA/ARAGUAINA, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/BUENOS_AIRES, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/CATAMARCA, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/CORDOBA, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/JUJUY, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/LA_RIOJA, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/MENDOZA, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/RIO_GALLEGOS, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/SALTA, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/SAN_JUAN, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/SAN_LUIS, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/TUCUMAN, //TODO: Write general description for this element
    ENUM_AMERICA/ARGENTINA/USHUAIA, //TODO: Write general description for this element
    ENUM_AMERICA/ARUBA, //TODO: Write general description for this element
    ENUM_AMERICA/ASUNCION, //TODO: Write general description for this element
    ENUM_AMERICA/ATIKOKAN, //TODO: Write general description for this element
    ENUM_AMERICA/BAHIA, //TODO: Write general description for this element
    ENUM_AMERICA/BAHIA_BANDERAS, //TODO: Write general description for this element
    ENUM_AMERICA/BARBADOS, //TODO: Write general description for this element
    ENUM_AMERICA/BELEM, //TODO: Write general description for this element
    ENUM_AMERICA/BELIZE, //TODO: Write general description for this element
    ENUM_AMERICA/BLANC-SABLON, //TODO: Write general description for this element
    ENUM_AMERICA/BOA_VISTA, //TODO: Write general description for this element
    ENUM_AMERICA/BOGOTA, //TODO: Write general description for this element
    ENUM_AMERICA/BOISE, //TODO: Write general description for this element
    ENUM_AMERICA/CAMBRIDGE_BAY, //TODO: Write general description for this element
    ENUM_AMERICA/CAMPO_GRANDE, //TODO: Write general description for this element
    ENUM_AMERICA/CANCUN, //TODO: Write general description for this element
    ENUM_AMERICA/CARACAS, //TODO: Write general description for this element
    ENUM_AMERICA/CAYENNE, //TODO: Write general description for this element
    ENUM_AMERICA/CAYMAN, //TODO: Write general description for this element
    ENUM_AMERICA/CHICAGO, //TODO: Write general description for this element
    ENUM_AMERICA/CHIHUAHUA, //TODO: Write general description for this element
    ENUM_AMERICA/COSTA_RICA, //TODO: Write general description for this element
    ENUM_AMERICA/CRESTON, //TODO: Write general description for this element
    ENUM_AMERICA/CUIABA, //TODO: Write general description for this element
    ENUM_AMERICA/CURACAO, //TODO: Write general description for this element
    ENUM_AMERICA/DANMARKSHAVN, //TODO: Write general description for this element
    ENUM_AMERICA/DAWSON, //TODO: Write general description for this element
    ENUM_AMERICA/DAWSON_CREEK, //TODO: Write general description for this element
    ENUM_AMERICA/DENVER, //TODO: Write general description for this element
    ENUM_AMERICA/DETROIT, //TODO: Write general description for this element
    ENUM_AMERICA/DOMINICA, //TODO: Write general description for this element
    ENUM_AMERICA/EDMONTON, //TODO: Write general description for this element
    ENUM_AMERICA/EIRUNEPE, //TODO: Write general description for this element
    ENUM_AMERICA/EL_SALVADOR, //TODO: Write general description for this element
    ENUM_AMERICA/FORTALEZA, //TODO: Write general description for this element
    ENUM_AMERICA/GLACE_BAY, //TODO: Write general description for this element
    ENUM_AMERICA/GODTHAB, //TODO: Write general description for this element
    ENUM_AMERICA/GOOSE_BAY, //TODO: Write general description for this element
    ENUM_AMERICA/GRAND_TURK, //TODO: Write general description for this element
    ENUM_AMERICA/GRENADA, //TODO: Write general description for this element
    ENUM_AMERICA/GUADELOUPE, //TODO: Write general description for this element
    ENUM_AMERICA/GUATEMALA, //TODO: Write general description for this element
    ENUM_AMERICA/GUAYAQUIL, //TODO: Write general description for this element
    ENUM_AMERICA/GUYANA, //TODO: Write general description for this element
    ENUM_AMERICA/HALIFAX, //TODO: Write general description for this element
    ENUM_AMERICA/HAVANA, //TODO: Write general description for this element
    ENUM_AMERICA/HERMOSILLO, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/INDIANAPOLIS, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/KNOX, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/MARENGO, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/PETERSBURG, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/TELL_CITY, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/VEVAY, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/VINCENNES, //TODO: Write general description for this element
    ENUM_AMERICA/INDIANA/WINAMAC, //TODO: Write general description for this element
    ENUM_AMERICA/INUVIK, //TODO: Write general description for this element
    ENUM_AMERICA/IQALUIT, //TODO: Write general description for this element
    ENUM_AMERICA/JAMAICA, //TODO: Write general description for this element
    ENUM_AMERICA/JUNEAU, //TODO: Write general description for this element
    ENUM_AMERICA/KENTUCKY/LOUISVILLE, //TODO: Write general description for this element
    ENUM_AMERICA/KENTUCKY/MONTICELLO, //TODO: Write general description for this element
    ENUM_AMERICA/KRALENDIJK, //TODO: Write general description for this element
    ENUM_AMERICA/LA_PAZ, //TODO: Write general description for this element
    ENUM_AMERICA/LIMA, //TODO: Write general description for this element
    ENUM_AMERICA/LOS_ANGELES, //TODO: Write general description for this element
    ENUM_AMERICA/LOWER_PRINCES, //TODO: Write general description for this element
    ENUM_AMERICA/MACEIO, //TODO: Write general description for this element
    ENUM_AMERICA/MANAGUA, //TODO: Write general description for this element
    ENUM_AMERICA/MANAUS, //TODO: Write general description for this element
    ENUM_AMERICA/MARIGOT, //TODO: Write general description for this element
    ENUM_AMERICA/MARTINIQUE, //TODO: Write general description for this element
    ENUM_AMERICA/MATAMOROS, //TODO: Write general description for this element
    ENUM_AMERICA/MAZATLAN, //TODO: Write general description for this element
    ENUM_AMERICA/MENOMINEE, //TODO: Write general description for this element
    ENUM_AMERICA/MERIDA, //TODO: Write general description for this element
    ENUM_AMERICA/METLAKATLA, //TODO: Write general description for this element
    ENUM_AMERICA/MEXICO_CITY, //TODO: Write general description for this element
    ENUM_AMERICA/MIQUELON, //TODO: Write general description for this element
    ENUM_AMERICA/MONCTON, //TODO: Write general description for this element
    ENUM_AMERICA/MONTERREY, //TODO: Write general description for this element
    ENUM_AMERICA/MONTEVIDEO, //TODO: Write general description for this element
    ENUM_AMERICA/MONTSERRAT, //TODO: Write general description for this element
    ENUM_AMERICA/NASSAU, //TODO: Write general description for this element
    ENUM_AMERICA/NEW_YORK, //TODO: Write general description for this element
    ENUM_AMERICA/NIPIGON, //TODO: Write general description for this element
    ENUM_AMERICA/NOME, //TODO: Write general description for this element
    ENUM_AMERICA/NORONHA, //TODO: Write general description for this element
    ENUM_AMERICA/NORTH_DAKOTA/BEULAH, //TODO: Write general description for this element
    ENUM_AMERICA/NORTH_DAKOTA/CENTER, //TODO: Write general description for this element
    ENUM_AMERICA/NORTH_DAKOTA/NEW_SALEM, //TODO: Write general description for this element
    ENUM_AMERICA/OJINAGA, //TODO: Write general description for this element
    ENUM_AMERICA/PANAMA, //TODO: Write general description for this element
    ENUM_AMERICA/PANGNIRTUNG, //TODO: Write general description for this element
    ENUM_AMERICA/PARAMARIBO, //TODO: Write general description for this element
    ENUM_AMERICA/PHOENIX, //TODO: Write general description for this element
    ENUM_AMERICA/PORT-AU-PRINCE, //TODO: Write general description for this element
    ENUM_AMERICA/PORT_OF_SPAIN, //TODO: Write general description for this element
    ENUM_AMERICA/PORTO_VELHO, //TODO: Write general description for this element
    ENUM_AMERICA/PUERTO_RICO, //TODO: Write general description for this element
    ENUM_AMERICA/RAINY_RIVER, //TODO: Write general description for this element
    ENUM_AMERICA/RANKIN_INLET, //TODO: Write general description for this element
    ENUM_AMERICA/RECIFE, //TODO: Write general description for this element
    ENUM_AMERICA/REGINA, //TODO: Write general description for this element
    ENUM_AMERICA/RESOLUTE, //TODO: Write general description for this element
    ENUM_AMERICA/RIO_BRANCO, //TODO: Write general description for this element
    ENUM_AMERICA/SANTA_ISABEL, //TODO: Write general description for this element
    ENUM_AMERICA/SANTAREM, //TODO: Write general description for this element
    ENUM_AMERICA/SANTIAGO, //TODO: Write general description for this element
    ENUM_AMERICA/SANTO_DOMINGO, //TODO: Write general description for this element
    ENUM_AMERICA/SAO_PAULO, //TODO: Write general description for this element
    ENUM_AMERICA/SCORESBYSUND, //TODO: Write general description for this element
    ENUM_AMERICA/SITKA, //TODO: Write general description for this element
    ENUM_AMERICA/ST_BARTHELEMY, //TODO: Write general description for this element
    ENUM_AMERICA/ST_JOHNS, //TODO: Write general description for this element
    ENUM_AMERICA/ST_KITTS, //TODO: Write general description for this element
    ENUM_AMERICA/ST_LUCIA, //TODO: Write general description for this element
    ENUM_AMERICA/ST_THOMAS, //TODO: Write general description for this element
    ENUM_AMERICA/ST_VINCENT, //TODO: Write general description for this element
    ENUM_AMERICA/SWIFT_CURRENT, //TODO: Write general description for this element
    ENUM_AMERICA/TEGUCIGALPA, //TODO: Write general description for this element
    ENUM_AMERICA/THULE, //TODO: Write general description for this element
    ENUM_AMERICA/THUNDER_BAY, //TODO: Write general description for this element
    ENUM_AMERICA/TIJUANA, //TODO: Write general description for this element
    ENUM_AMERICA/TORONTO, //TODO: Write general description for this element
    ENUM_AMERICA/TORTOLA, //TODO: Write general description for this element
    ENUM_AMERICA/VANCOUVER, //TODO: Write general description for this element
    ENUM_AMERICA/WHITEHORSE, //TODO: Write general description for this element
    ENUM_AMERICA/WINNIPEG, //TODO: Write general description for this element
    ENUM_AMERICA/YAKUTAT, //TODO: Write general description for this element
    ENUM_AMERICA/YELLOWKNIFE, //TODO: Write general description for this element
    ENUM_ANTARCTICA/CASEY, //TODO: Write general description for this element
    ENUM_ANTARCTICA/DAVIS, //TODO: Write general description for this element
    ENUM_ANTARCTICA/DUMONTDURVILLE, //TODO: Write general description for this element
    ENUM_ANTARCTICA/MACQUARIE, //TODO: Write general description for this element
    ENUM_ANTARCTICA/MAWSON, //TODO: Write general description for this element
    ENUM_ANTARCTICA/MCMURDO, //TODO: Write general description for this element
    ENUM_ANTARCTICA/PALMER, //TODO: Write general description for this element
    ENUM_ANTARCTICA/ROTHERA, //TODO: Write general description for this element
    ENUM_ANTARCTICA/SYOWA, //TODO: Write general description for this element
    ENUM_ANTARCTICA/TROLL, //TODO: Write general description for this element
    ENUM_ANTARCTICA/VOSTOK, //TODO: Write general description for this element
    ENUM_ARCTIC/LONGYEARBYEN, //TODO: Write general description for this element
    ENUM_ASIA/ADEN, //TODO: Write general description for this element
    ENUM_ASIA/ALMATY, //TODO: Write general description for this element
    ENUM_ASIA/AMMAN, //TODO: Write general description for this element
    ENUM_ASIA/ANADYR, //TODO: Write general description for this element
    ENUM_ASIA/AQTAU, //TODO: Write general description for this element
    ENUM_ASIA/AQTOBE, //TODO: Write general description for this element
    ENUM_ASIA/ASHGABAT, //TODO: Write general description for this element
    ENUM_ASIA/BAGHDAD, //TODO: Write general description for this element
    ENUM_ASIA/BAHRAIN, //TODO: Write general description for this element
    ENUM_ASIA/BAKU, //TODO: Write general description for this element
    ENUM_ASIA/BANGKOK, //TODO: Write general description for this element
    ENUM_ASIA/BEIRUT, //TODO: Write general description for this element
    ENUM_ASIA/BISHKEK, //TODO: Write general description for this element
    ENUM_ASIA/BRUNEI, //TODO: Write general description for this element
    ENUM_ASIA/CHOIBALSAN, //TODO: Write general description for this element
    ENUM_ASIA/CHONGQING, //TODO: Write general description for this element
    ENUM_ASIA/COLOMBO, //TODO: Write general description for this element
    ENUM_ASIA/DAMASCUS, //TODO: Write general description for this element
    ENUM_ASIA/DHAKA, //TODO: Write general description for this element
    ENUM_ASIA/DILI, //TODO: Write general description for this element
    ENUM_ASIA/DUBAI, //TODO: Write general description for this element
    ENUM_ASIA/DUSHANBE, //TODO: Write general description for this element
    ENUM_ASIA/GAZA, //TODO: Write general description for this element
    ENUM_ASIA/HARBIN, //TODO: Write general description for this element
    ENUM_ASIA/HEBRON, //TODO: Write general description for this element
    ENUM_ASIA/HO_CHI_MINH, //TODO: Write general description for this element
    ENUM_ASIA/HONG_KONG, //TODO: Write general description for this element
    ENUM_ASIA/HOVD, //TODO: Write general description for this element
    ENUM_ASIA/IRKUTSK, //TODO: Write general description for this element
    ENUM_ASIA/JAKARTA, //TODO: Write general description for this element
    ENUM_ASIA/JAYAPURA, //TODO: Write general description for this element
    ENUM_ASIA/JERUSALEM, //TODO: Write general description for this element
    ENUM_ASIA/KABUL, //TODO: Write general description for this element
    ENUM_ASIA/KAMCHATKA, //TODO: Write general description for this element
    ENUM_ASIA/KARACHI, //TODO: Write general description for this element
    ENUM_ASIA/KASHGAR, //TODO: Write general description for this element
    ENUM_ASIA/KATHMANDU, //TODO: Write general description for this element
    ENUM_ASIA/KHANDYGA, //TODO: Write general description for this element
    ENUM_ASIA/KOLKATA, //TODO: Write general description for this element
    ENUM_ASIA/KRASNOYARSK, //TODO: Write general description for this element
    ENUM_ASIA/KUALA_LUMPUR, //TODO: Write general description for this element
    ENUM_ASIA/KUCHING, //TODO: Write general description for this element
    ENUM_ASIA/KUWAIT, //TODO: Write general description for this element
    ENUM_ASIA/MACAU, //TODO: Write general description for this element
    ENUM_ASIA/MAGADAN, //TODO: Write general description for this element
    ENUM_ASIA/MAKASSAR, //TODO: Write general description for this element
    ENUM_ASIA/MANILA, //TODO: Write general description for this element
    ENUM_ASIA/MUSCAT, //TODO: Write general description for this element
    ENUM_ASIA/NICOSIA, //TODO: Write general description for this element
    ENUM_ASIA/NOVOKUZNETSK, //TODO: Write general description for this element
    ENUM_ASIA/NOVOSIBIRSK, //TODO: Write general description for this element
    ENUM_ASIA/OMSK, //TODO: Write general description for this element
    ENUM_ASIA/ORAL, //TODO: Write general description for this element
    ENUM_ASIA/PHNOM_PENH, //TODO: Write general description for this element
    ENUM_ASIA/PONTIANAK, //TODO: Write general description for this element
    ENUM_ASIA/PYONGYANG, //TODO: Write general description for this element
    ENUM_ASIA/QATAR, //TODO: Write general description for this element
    ENUM_ASIA/QYZYLORDA, //TODO: Write general description for this element
    ENUM_ASIA/RANGOON, //TODO: Write general description for this element
    ENUM_ASIA/RIYADH, //TODO: Write general description for this element
    ENUM_ASIA/SAKHALIN, //TODO: Write general description for this element
    ENUM_ASIA/SAMARKAND, //TODO: Write general description for this element
    ENUM_ASIA/SEOUL, //TODO: Write general description for this element
    ENUM_ASIA/SHANGHAI, //TODO: Write general description for this element
    ENUM_ASIA/SINGAPORE, //TODO: Write general description for this element
    ENUM_ASIA/TAIPEI, //TODO: Write general description for this element
    ENUM_ASIA/TASHKENT, //TODO: Write general description for this element
    ENUM_ASIA/TBILISI, //TODO: Write general description for this element
    ENUM_ASIA/TEHRAN, //TODO: Write general description for this element
    ENUM_ASIA/THIMPHU, //TODO: Write general description for this element
    ENUM_ASIA/TOKYO, //TODO: Write general description for this element
    ENUM_ASIA/ULAANBAATAR, //TODO: Write general description for this element
    ENUM_ASIA/URUMQI, //TODO: Write general description for this element
    ENUM_ASIA/UST-NERA, //TODO: Write general description for this element
    ENUM_ASIA/VIENTIANE, //TODO: Write general description for this element
    ENUM_ASIA/VLADIVOSTOK, //TODO: Write general description for this element
    ENUM_ASIA/YAKUTSK, //TODO: Write general description for this element
    ENUM_ASIA/YEKATERINBURG, //TODO: Write general description for this element
    ENUM_ASIA/YEREVAN, //TODO: Write general description for this element
    ENUM_ATLANTIC/AZORES, //TODO: Write general description for this element
    ENUM_ATLANTIC/BERMUDA, //TODO: Write general description for this element
    ENUM_ATLANTIC/CANARY, //TODO: Write general description for this element
    ENUM_ATLANTIC/CAPE_VERDE, //TODO: Write general description for this element
    ENUM_ATLANTIC/FAROE, //TODO: Write general description for this element
    ENUM_ATLANTIC/MADEIRA, //TODO: Write general description for this element
    ENUM_ATLANTIC/REYKJAVIK, //TODO: Write general description for this element
    ENUM_ATLANTIC/SOUTH_GEORGIA, //TODO: Write general description for this element
    ENUM_ATLANTIC/ST_HELENA, //TODO: Write general description for this element
    ENUM_ATLANTIC/STANLEY, //TODO: Write general description for this element
    ENUM_AUSTRALIA/ADELAIDE, //TODO: Write general description for this element
    ENUM_AUSTRALIA/BRISBANE, //TODO: Write general description for this element
    ENUM_AUSTRALIA/BROKEN_HILL, //TODO: Write general description for this element
    ENUM_AUSTRALIA/CURRIE, //TODO: Write general description for this element
    ENUM_AUSTRALIA/DARWIN, //TODO: Write general description for this element
    ENUM_AUSTRALIA/EUCLA, //TODO: Write general description for this element
    ENUM_AUSTRALIA/HOBART, //TODO: Write general description for this element
    ENUM_AUSTRALIA/LINDEMAN, //TODO: Write general description for this element
    ENUM_AUSTRALIA/LORD_HOWE, //TODO: Write general description for this element
    ENUM_AUSTRALIA/MELBOURNE, //TODO: Write general description for this element
    ENUM_AUSTRALIA/PERTH, //TODO: Write general description for this element
    ENUM_AUSTRALIA/SYDNEY, //TODO: Write general description for this element
    ENUM_EUROPE/AMSTERDAM, //TODO: Write general description for this element
    ENUM_EUROPE/ANDORRA, //TODO: Write general description for this element
    ENUM_EUROPE/ATHENS, //TODO: Write general description for this element
    ENUM_EUROPE/BELGRADE, //TODO: Write general description for this element
    ENUM_EUROPE/BERLIN, //TODO: Write general description for this element
    ENUM_EUROPE/BRATISLAVA, //TODO: Write general description for this element
    ENUM_EUROPE/BRUSSELS, //TODO: Write general description for this element
    ENUM_EUROPE/BUCHAREST, //TODO: Write general description for this element
    ENUM_EUROPE/BUDAPEST, //TODO: Write general description for this element
    ENUM_EUROPE/BUSINGEN, //TODO: Write general description for this element
    ENUM_EUROPE/CHISINAU, //TODO: Write general description for this element
    ENUM_EUROPE/COPENHAGEN, //TODO: Write general description for this element
    ENUM_EUROPE/DUBLIN, //TODO: Write general description for this element
    ENUM_EUROPE/GIBRALTAR, //TODO: Write general description for this element
    ENUM_EUROPE/GUERNSEY, //TODO: Write general description for this element
    ENUM_EUROPE/HELSINKI, //TODO: Write general description for this element
    ENUM_EUROPE/ISLE_OF_MAN, //TODO: Write general description for this element
    ENUM_EUROPE/ISTANBUL, //TODO: Write general description for this element
    ENUM_EUROPE/JERSEY, //TODO: Write general description for this element
    ENUM_EUROPE/KALININGRAD, //TODO: Write general description for this element
    ENUM_EUROPE/KIEV, //TODO: Write general description for this element
    ENUM_EUROPE/LISBON, //TODO: Write general description for this element
    ENUM_EUROPE/LJUBLJANA, //TODO: Write general description for this element
    ENUM_EUROPE/LONDON, //TODO: Write general description for this element
    ENUM_EUROPE/LUXEMBOURG, //TODO: Write general description for this element
    ENUM_EUROPE/MADRID, //TODO: Write general description for this element
    ENUM_EUROPE/MALTA, //TODO: Write general description for this element
    ENUM_EUROPE/MARIEHAMN, //TODO: Write general description for this element
    ENUM_EUROPE/MINSK, //TODO: Write general description for this element
    ENUM_EUROPE/MONACO, //TODO: Write general description for this element
    ENUM_EUROPE/MOSCOW, //TODO: Write general description for this element
    ENUM_EUROPE/OSLO, //TODO: Write general description for this element
    ENUM_EUROPE/PARIS, //TODO: Write general description for this element
    ENUM_EUROPE/PODGORICA, //TODO: Write general description for this element
    ENUM_EUROPE/PRAGUE, //TODO: Write general description for this element
    ENUM_EUROPE/RIGA, //TODO: Write general description for this element
    ENUM_EUROPE/ROME, //TODO: Write general description for this element
    ENUM_EUROPE/SAMARA, //TODO: Write general description for this element
    ENUM_EUROPE/SAN_MARINO, //TODO: Write general description for this element
    ENUM_EUROPE/SARAJEVO, //TODO: Write general description for this element
    ENUM_EUROPE/SIMFEROPOL, //TODO: Write general description for this element
    ENUM_EUROPE/SKOPJE, //TODO: Write general description for this element
    ENUM_EUROPE/SOFIA, //TODO: Write general description for this element
    ENUM_EUROPE/STOCKHOLM, //TODO: Write general description for this element
    ENUM_EUROPE/TALLINN, //TODO: Write general description for this element
    ENUM_EUROPE/TIRANE, //TODO: Write general description for this element
    ENUM_EUROPE/UZHGOROD, //TODO: Write general description for this element
    ENUM_EUROPE/VADUZ, //TODO: Write general description for this element
    ENUM_EUROPE/VATICAN, //TODO: Write general description for this element
    ENUM_EUROPE/VIENNA, //TODO: Write general description for this element
    ENUM_EUROPE/VILNIUS, //TODO: Write general description for this element
    ENUM_EUROPE/VOLGOGRAD, //TODO: Write general description for this element
    ENUM_EUROPE/WARSAW, //TODO: Write general description for this element
    ENUM_EUROPE/ZAGREB, //TODO: Write general description for this element
    ENUM_EUROPE/ZAPOROZHYE, //TODO: Write general description for this element
    ENUM_EUROPE/ZURICH, //TODO: Write general description for this element
    GMT, //TODO: Write general description for this element
    ENUM_INDIAN/ANTANANARIVO, //TODO: Write general description for this element
    ENUM_INDIAN/CHAGOS, //TODO: Write general description for this element
    ENUM_INDIAN/CHRISTMAS, //TODO: Write general description for this element
    ENUM_INDIAN/COCOS, //TODO: Write general description for this element
    ENUM_INDIAN/COMORO, //TODO: Write general description for this element
    ENUM_INDIAN/KERGUELEN, //TODO: Write general description for this element
    ENUM_INDIAN/MAHE, //TODO: Write general description for this element
    ENUM_INDIAN/MALDIVES, //TODO: Write general description for this element
    ENUM_INDIAN/MAURITIUS, //TODO: Write general description for this element
    ENUM_INDIAN/MAYOTTE, //TODO: Write general description for this element
    ENUM_INDIAN/REUNION, //TODO: Write general description for this element
    ENUM_PACIFIC/APIA, //TODO: Write general description for this element
    ENUM_PACIFIC/AUCKLAND, //TODO: Write general description for this element
    ENUM_PACIFIC/CHATHAM, //TODO: Write general description for this element
    ENUM_PACIFIC/CHUUK, //TODO: Write general description for this element
    ENUM_PACIFIC/EASTER, //TODO: Write general description for this element
    ENUM_PACIFIC/EFATE, //TODO: Write general description for this element
    ENUM_PACIFIC/ENDERBURY, //TODO: Write general description for this element
    ENUM_PACIFIC/FAKAOFO, //TODO: Write general description for this element
    ENUM_PACIFIC/FIJI, //TODO: Write general description for this element
    ENUM_PACIFIC/FUNAFUTI, //TODO: Write general description for this element
    ENUM_PACIFIC/GALAPAGOS, //TODO: Write general description for this element
    ENUM_PACIFIC/GAMBIER, //TODO: Write general description for this element
    ENUM_PACIFIC/GUADALCANAL, //TODO: Write general description for this element
    ENUM_PACIFIC/GUAM, //TODO: Write general description for this element
    ENUM_PACIFIC/HONOLULU, //TODO: Write general description for this element
    ENUM_PACIFIC/JOHNSTON, //TODO: Write general description for this element
    ENUM_PACIFIC/KIRITIMATI, //TODO: Write general description for this element
    ENUM_PACIFIC/KOSRAE, //TODO: Write general description for this element
    ENUM_PACIFIC/KWAJALEIN, //TODO: Write general description for this element
    ENUM_PACIFIC/MAJURO, //TODO: Write general description for this element
    ENUM_PACIFIC/MARQUESAS, //TODO: Write general description for this element
    ENUM_PACIFIC/MIDWAY, //TODO: Write general description for this element
    ENUM_PACIFIC/NAURU, //TODO: Write general description for this element
    ENUM_PACIFIC/NIUE, //TODO: Write general description for this element
    ENUM_PACIFIC/NORFOLK, //TODO: Write general description for this element
    ENUM_PACIFIC/NOUMEA, //TODO: Write general description for this element
    ENUM_PACIFIC/PAGO_PAGO, //TODO: Write general description for this element
    ENUM_PACIFIC/PALAU, //TODO: Write general description for this element
    ENUM_PACIFIC/PITCAIRN, //TODO: Write general description for this element
    ENUM_PACIFIC/POHNPEI, //TODO: Write general description for this element
    ENUM_PACIFIC/PORT_MORESBY, //TODO: Write general description for this element
    ENUM_PACIFIC/RAROTONGA, //TODO: Write general description for this element
    ENUM_PACIFIC/SAIPAN, //TODO: Write general description for this element
    ENUM_PACIFIC/TAHITI, //TODO: Write general description for this element
    ENUM_PACIFIC/TARAWA, //TODO: Write general description for this element
    ENUM_PACIFIC/TONGATAPU, //TODO: Write general description for this element
    ENUM_PACIFIC/WAKE, //TODO: Write general description for this element
    ENUM_PACIFIC/WALLIS; //TODO: Write general description for this element

    private static TreeMap<String, TimezoneEnum> valueMap = new TreeMap<String, TimezoneEnum>();
    private String value;

    static {
        ENUM_AFRICA/ABIDJAN.value = "Africa/Abidjan";
        ENUM_AFRICA/ACCRA.value = "Africa/Accra";
        ENUM_AFRICA/ADDIS_ABABA.value = "Africa/Addis_Ababa";
        ENUM_AFRICA/ALGIERS.value = "Africa/Algiers";
        ENUM_AFRICA/ASMARA.value = "Africa/Asmara";
        ENUM_AFRICA/BAMAKO.value = "Africa/Bamako";
        ENUM_AFRICA/BANGUI.value = "Africa/Bangui";
        ENUM_AFRICA/BANJUL.value = "Africa/Banjul";
        ENUM_AFRICA/BISSAU.value = "Africa/Bissau";
        ENUM_AFRICA/BLANTYRE.value = "Africa/Blantyre";
        ENUM_AFRICA/BRAZZAVILLE.value = "Africa/Brazzaville";
        ENUM_AFRICA/BUJUMBURA.value = "Africa/Bujumbura";
        ENUM_AFRICA/CAIRO.value = "Africa/Cairo";
        ENUM_AFRICA/CASABLANCA.value = "Africa/Casablanca";
        ENUM_AFRICA/CEUTA.value = "Africa/Ceuta";
        ENUM_AFRICA/CONAKRY.value = "Africa/Conakry";
        ENUM_AFRICA/DAKAR.value = "Africa/Dakar";
        ENUM_AFRICA/DAR_ES_SALAAM.value = "Africa/Dar_es_Salaam";
        ENUM_AFRICA/DJIBOUTI.value = "Africa/Djibouti";
        ENUM_AFRICA/DOUALA.value = "Africa/Douala";
        ENUM_AFRICA/EL_AAIUN.value = "Africa/El_Aaiun";
        ENUM_AFRICA/FREETOWN.value = "Africa/Freetown";
        ENUM_AFRICA/GABORONE.value = "Africa/Gaborone";
        ENUM_AFRICA/HARARE.value = "Africa/Harare";
        ENUM_AFRICA/JOHANNESBURG.value = "Africa/Johannesburg";
        ENUM_AFRICA/JUBA.value = "Africa/Juba";
        ENUM_AFRICA/KAMPALA.value = "Africa/Kampala";
        ENUM_AFRICA/KHARTOUM.value = "Africa/Khartoum";
        ENUM_AFRICA/KIGALI.value = "Africa/Kigali";
        ENUM_AFRICA/KINSHASA.value = "Africa/Kinshasa";
        ENUM_AFRICA/LAGOS.value = "Africa/Lagos";
        ENUM_AFRICA/LIBREVILLE.value = "Africa/Libreville";
        ENUM_AFRICA/LOME.value = "Africa/Lome";
        ENUM_AFRICA/LUANDA.value = "Africa/Luanda";
        ENUM_AFRICA/LUBUMBASHI.value = "Africa/Lubumbashi";
        ENUM_AFRICA/LUSAKA.value = "Africa/Lusaka";
        ENUM_AFRICA/MALABO.value = "Africa/Malabo";
        ENUM_AFRICA/MAPUTO.value = "Africa/Maputo";
        ENUM_AFRICA/MASERU.value = "Africa/Maseru";
        ENUM_AFRICA/MBABANE.value = "Africa/Mbabane";
        ENUM_AFRICA/MOGADISHU.value = "Africa/Mogadishu";
        ENUM_AFRICA/MONROVIA.value = "Africa/Monrovia";
        ENUM_AFRICA/NAIROBI.value = "Africa/Nairobi";
        ENUM_AFRICA/NDJAMENA.value = "Africa/Ndjamena";
        ENUM_AFRICA/NIAMEY.value = "Africa/Niamey";
        ENUM_AFRICA/NOUAKCHOTT.value = "Africa/Nouakchott";
        ENUM_AFRICA/OUAGADOUGOU.value = "Africa/Ouagadougou";
        ENUM_AFRICA/PORTO-NOVO.value = "Africa/Porto-Novo";
        ENUM_AFRICA/SAO_TOME.value = "Africa/Sao_Tome";
        ENUM_AFRICA/TRIPOLI.value = "Africa/Tripoli";
        ENUM_AFRICA/TUNIS.value = "Africa/Tunis";
        ENUM_AFRICA/WINDHOEK.value = "Africa/Windhoek";
        ENUM_AMERICA/ADAK.value = "America/Adak";
        ENUM_AMERICA/ANCHORAGE.value = "America/Anchorage";
        ENUM_AMERICA/ANGUILLA.value = "America/Anguilla";
        ENUM_AMERICA/ANTIGUA.value = "America/Antigua";
        ENUM_AMERICA/ARAGUAINA.value = "America/Araguaina";
        ENUM_AMERICA/ARGENTINA/BUENOS_AIRES.value = "America/Argentina/Buenos_Aires";
        ENUM_AMERICA/ARGENTINA/CATAMARCA.value = "America/Argentina/Catamarca";
        ENUM_AMERICA/ARGENTINA/CORDOBA.value = "America/Argentina/Cordoba";
        ENUM_AMERICA/ARGENTINA/JUJUY.value = "America/Argentina/Jujuy";
        ENUM_AMERICA/ARGENTINA/LA_RIOJA.value = "America/Argentina/La_Rioja";
        ENUM_AMERICA/ARGENTINA/MENDOZA.value = "America/Argentina/Mendoza";
        ENUM_AMERICA/ARGENTINA/RIO_GALLEGOS.value = "America/Argentina/Rio_Gallegos";
        ENUM_AMERICA/ARGENTINA/SALTA.value = "America/Argentina/Salta";
        ENUM_AMERICA/ARGENTINA/SAN_JUAN.value = "America/Argentina/San_Juan";
        ENUM_AMERICA/ARGENTINA/SAN_LUIS.value = "America/Argentina/San_Luis";
        ENUM_AMERICA/ARGENTINA/TUCUMAN.value = "America/Argentina/Tucuman";
        ENUM_AMERICA/ARGENTINA/USHUAIA.value = "America/Argentina/Ushuaia";
        ENUM_AMERICA/ARUBA.value = "America/Aruba";
        ENUM_AMERICA/ASUNCION.value = "America/Asuncion";
        ENUM_AMERICA/ATIKOKAN.value = "America/Atikokan";
        ENUM_AMERICA/BAHIA.value = "America/Bahia";
        ENUM_AMERICA/BAHIA_BANDERAS.value = "America/Bahia_Banderas";
        ENUM_AMERICA/BARBADOS.value = "America/Barbados";
        ENUM_AMERICA/BELEM.value = "America/Belem";
        ENUM_AMERICA/BELIZE.value = "America/Belize";
        ENUM_AMERICA/BLANC-SABLON.value = "America/Blanc-Sablon";
        ENUM_AMERICA/BOA_VISTA.value = "America/Boa_Vista";
        ENUM_AMERICA/BOGOTA.value = "America/Bogota";
        ENUM_AMERICA/BOISE.value = "America/Boise";
        ENUM_AMERICA/CAMBRIDGE_BAY.value = "America/Cambridge_Bay";
        ENUM_AMERICA/CAMPO_GRANDE.value = "America/Campo_Grande";
        ENUM_AMERICA/CANCUN.value = "America/Cancun";
        ENUM_AMERICA/CARACAS.value = "America/Caracas";
        ENUM_AMERICA/CAYENNE.value = "America/Cayenne";
        ENUM_AMERICA/CAYMAN.value = "America/Cayman";
        ENUM_AMERICA/CHICAGO.value = "America/Chicago";
        ENUM_AMERICA/CHIHUAHUA.value = "America/Chihuahua";
        ENUM_AMERICA/COSTA_RICA.value = "America/Costa_Rica";
        ENUM_AMERICA/CRESTON.value = "America/Creston";
        ENUM_AMERICA/CUIABA.value = "America/Cuiaba";
        ENUM_AMERICA/CURACAO.value = "America/Curacao";
        ENUM_AMERICA/DANMARKSHAVN.value = "America/Danmarkshavn";
        ENUM_AMERICA/DAWSON.value = "America/Dawson";
        ENUM_AMERICA/DAWSON_CREEK.value = "America/Dawson_Creek";
        ENUM_AMERICA/DENVER.value = "America/Denver";
        ENUM_AMERICA/DETROIT.value = "America/Detroit";
        ENUM_AMERICA/DOMINICA.value = "America/Dominica";
        ENUM_AMERICA/EDMONTON.value = "America/Edmonton";
        ENUM_AMERICA/EIRUNEPE.value = "America/Eirunepe";
        ENUM_AMERICA/EL_SALVADOR.value = "America/El_Salvador";
        ENUM_AMERICA/FORTALEZA.value = "America/Fortaleza";
        ENUM_AMERICA/GLACE_BAY.value = "America/Glace_Bay";
        ENUM_AMERICA/GODTHAB.value = "America/Godthab";
        ENUM_AMERICA/GOOSE_BAY.value = "America/Goose_Bay";
        ENUM_AMERICA/GRAND_TURK.value = "America/Grand_Turk";
        ENUM_AMERICA/GRENADA.value = "America/Grenada";
        ENUM_AMERICA/GUADELOUPE.value = "America/Guadeloupe";
        ENUM_AMERICA/GUATEMALA.value = "America/Guatemala";
        ENUM_AMERICA/GUAYAQUIL.value = "America/Guayaquil";
        ENUM_AMERICA/GUYANA.value = "America/Guyana";
        ENUM_AMERICA/HALIFAX.value = "America/Halifax";
        ENUM_AMERICA/HAVANA.value = "America/Havana";
        ENUM_AMERICA/HERMOSILLO.value = "America/Hermosillo";
        ENUM_AMERICA/INDIANA/INDIANAPOLIS.value = "America/Indiana/Indianapolis";
        ENUM_AMERICA/INDIANA/KNOX.value = "America/Indiana/Knox";
        ENUM_AMERICA/INDIANA/MARENGO.value = "America/Indiana/Marengo";
        ENUM_AMERICA/INDIANA/PETERSBURG.value = "America/Indiana/Petersburg";
        ENUM_AMERICA/INDIANA/TELL_CITY.value = "America/Indiana/Tell_City";
        ENUM_AMERICA/INDIANA/VEVAY.value = "America/Indiana/Vevay";
        ENUM_AMERICA/INDIANA/VINCENNES.value = "America/Indiana/Vincennes";
        ENUM_AMERICA/INDIANA/WINAMAC.value = "America/Indiana/Winamac";
        ENUM_AMERICA/INUVIK.value = "America/Inuvik";
        ENUM_AMERICA/IQALUIT.value = "America/Iqaluit";
        ENUM_AMERICA/JAMAICA.value = "America/Jamaica";
        ENUM_AMERICA/JUNEAU.value = "America/Juneau";
        ENUM_AMERICA/KENTUCKY/LOUISVILLE.value = "America/Kentucky/Louisville";
        ENUM_AMERICA/KENTUCKY/MONTICELLO.value = "America/Kentucky/Monticello";
        ENUM_AMERICA/KRALENDIJK.value = "America/Kralendijk";
        ENUM_AMERICA/LA_PAZ.value = "America/La_Paz";
        ENUM_AMERICA/LIMA.value = "America/Lima";
        ENUM_AMERICA/LOS_ANGELES.value = "America/Los_Angeles";
        ENUM_AMERICA/LOWER_PRINCES.value = "America/Lower_Princes";
        ENUM_AMERICA/MACEIO.value = "America/Maceio";
        ENUM_AMERICA/MANAGUA.value = "America/Managua";
        ENUM_AMERICA/MANAUS.value = "America/Manaus";
        ENUM_AMERICA/MARIGOT.value = "America/Marigot";
        ENUM_AMERICA/MARTINIQUE.value = "America/Martinique";
        ENUM_AMERICA/MATAMOROS.value = "America/Matamoros";
        ENUM_AMERICA/MAZATLAN.value = "America/Mazatlan";
        ENUM_AMERICA/MENOMINEE.value = "America/Menominee";
        ENUM_AMERICA/MERIDA.value = "America/Merida";
        ENUM_AMERICA/METLAKATLA.value = "America/Metlakatla";
        ENUM_AMERICA/MEXICO_CITY.value = "America/Mexico_City";
        ENUM_AMERICA/MIQUELON.value = "America/Miquelon";
        ENUM_AMERICA/MONCTON.value = "America/Moncton";
        ENUM_AMERICA/MONTERREY.value = "America/Monterrey";
        ENUM_AMERICA/MONTEVIDEO.value = "America/Montevideo";
        ENUM_AMERICA/MONTSERRAT.value = "America/Montserrat";
        ENUM_AMERICA/NASSAU.value = "America/Nassau";
        ENUM_AMERICA/NEW_YORK.value = "America/New_York";
        ENUM_AMERICA/NIPIGON.value = "America/Nipigon";
        ENUM_AMERICA/NOME.value = "America/Nome";
        ENUM_AMERICA/NORONHA.value = "America/Noronha";
        ENUM_AMERICA/NORTH_DAKOTA/BEULAH.value = "America/North_Dakota/Beulah";
        ENUM_AMERICA/NORTH_DAKOTA/CENTER.value = "America/North_Dakota/Center";
        ENUM_AMERICA/NORTH_DAKOTA/NEW_SALEM.value = "America/North_Dakota/New_Salem";
        ENUM_AMERICA/OJINAGA.value = "America/Ojinaga";
        ENUM_AMERICA/PANAMA.value = "America/Panama";
        ENUM_AMERICA/PANGNIRTUNG.value = "America/Pangnirtung";
        ENUM_AMERICA/PARAMARIBO.value = "America/Paramaribo";
        ENUM_AMERICA/PHOENIX.value = "America/Phoenix";
        ENUM_AMERICA/PORT-AU-PRINCE.value = "America/Port-au-Prince";
        ENUM_AMERICA/PORT_OF_SPAIN.value = "America/Port_of_Spain";
        ENUM_AMERICA/PORTO_VELHO.value = "America/Porto_Velho";
        ENUM_AMERICA/PUERTO_RICO.value = "America/Puerto_Rico";
        ENUM_AMERICA/RAINY_RIVER.value = "America/Rainy_River";
        ENUM_AMERICA/RANKIN_INLET.value = "America/Rankin_Inlet";
        ENUM_AMERICA/RECIFE.value = "America/Recife";
        ENUM_AMERICA/REGINA.value = "America/Regina";
        ENUM_AMERICA/RESOLUTE.value = "America/Resolute";
        ENUM_AMERICA/RIO_BRANCO.value = "America/Rio_Branco";
        ENUM_AMERICA/SANTA_ISABEL.value = "America/Santa_Isabel";
        ENUM_AMERICA/SANTAREM.value = "America/Santarem";
        ENUM_AMERICA/SANTIAGO.value = "America/Santiago";
        ENUM_AMERICA/SANTO_DOMINGO.value = "America/Santo_Domingo";
        ENUM_AMERICA/SAO_PAULO.value = "America/Sao_Paulo";
        ENUM_AMERICA/SCORESBYSUND.value = "America/Scoresbysund";
        ENUM_AMERICA/SITKA.value = "America/Sitka";
        ENUM_AMERICA/ST_BARTHELEMY.value = "America/St_Barthelemy";
        ENUM_AMERICA/ST_JOHNS.value = "America/St_Johns";
        ENUM_AMERICA/ST_KITTS.value = "America/St_Kitts";
        ENUM_AMERICA/ST_LUCIA.value = "America/St_Lucia";
        ENUM_AMERICA/ST_THOMAS.value = "America/St_Thomas";
        ENUM_AMERICA/ST_VINCENT.value = "America/St_Vincent";
        ENUM_AMERICA/SWIFT_CURRENT.value = "America/Swift_Current";
        ENUM_AMERICA/TEGUCIGALPA.value = "America/Tegucigalpa";
        ENUM_AMERICA/THULE.value = "America/Thule";
        ENUM_AMERICA/THUNDER_BAY.value = "America/Thunder_Bay";
        ENUM_AMERICA/TIJUANA.value = "America/Tijuana";
        ENUM_AMERICA/TORONTO.value = "America/Toronto";
        ENUM_AMERICA/TORTOLA.value = "America/Tortola";
        ENUM_AMERICA/VANCOUVER.value = "America/Vancouver";
        ENUM_AMERICA/WHITEHORSE.value = "America/Whitehorse";
        ENUM_AMERICA/WINNIPEG.value = "America/Winnipeg";
        ENUM_AMERICA/YAKUTAT.value = "America/Yakutat";
        ENUM_AMERICA/YELLOWKNIFE.value = "America/Yellowknife";
        ENUM_ANTARCTICA/CASEY.value = "Antarctica/Casey";
        ENUM_ANTARCTICA/DAVIS.value = "Antarctica/Davis";
        ENUM_ANTARCTICA/DUMONTDURVILLE.value = "Antarctica/DumontDUrville";
        ENUM_ANTARCTICA/MACQUARIE.value = "Antarctica/Macquarie";
        ENUM_ANTARCTICA/MAWSON.value = "Antarctica/Mawson";
        ENUM_ANTARCTICA/MCMURDO.value = "Antarctica/McMurdo";
        ENUM_ANTARCTICA/PALMER.value = "Antarctica/Palmer";
        ENUM_ANTARCTICA/ROTHERA.value = "Antarctica/Rothera";
        ENUM_ANTARCTICA/SYOWA.value = "Antarctica/Syowa";
        ENUM_ANTARCTICA/TROLL.value = "Antarctica/Troll";
        ENUM_ANTARCTICA/VOSTOK.value = "Antarctica/Vostok";
        ENUM_ARCTIC/LONGYEARBYEN.value = "Arctic/Longyearbyen";
        ENUM_ASIA/ADEN.value = "Asia/Aden";
        ENUM_ASIA/ALMATY.value = "Asia/Almaty";
        ENUM_ASIA/AMMAN.value = "Asia/Amman";
        ENUM_ASIA/ANADYR.value = "Asia/Anadyr";
        ENUM_ASIA/AQTAU.value = "Asia/Aqtau";
        ENUM_ASIA/AQTOBE.value = "Asia/Aqtobe";
        ENUM_ASIA/ASHGABAT.value = "Asia/Ashgabat";
        ENUM_ASIA/BAGHDAD.value = "Asia/Baghdad";
        ENUM_ASIA/BAHRAIN.value = "Asia/Bahrain";
        ENUM_ASIA/BAKU.value = "Asia/Baku";
        ENUM_ASIA/BANGKOK.value = "Asia/Bangkok";
        ENUM_ASIA/BEIRUT.value = "Asia/Beirut";
        ENUM_ASIA/BISHKEK.value = "Asia/Bishkek";
        ENUM_ASIA/BRUNEI.value = "Asia/Brunei";
        ENUM_ASIA/CHOIBALSAN.value = "Asia/Choibalsan";
        ENUM_ASIA/CHONGQING.value = "Asia/Chongqing";
        ENUM_ASIA/COLOMBO.value = "Asia/Colombo";
        ENUM_ASIA/DAMASCUS.value = "Asia/Damascus";
        ENUM_ASIA/DHAKA.value = "Asia/Dhaka";
        ENUM_ASIA/DILI.value = "Asia/Dili";
        ENUM_ASIA/DUBAI.value = "Asia/Dubai";
        ENUM_ASIA/DUSHANBE.value = "Asia/Dushanbe";
        ENUM_ASIA/GAZA.value = "Asia/Gaza";
        ENUM_ASIA/HARBIN.value = "Asia/Harbin";
        ENUM_ASIA/HEBRON.value = "Asia/Hebron";
        ENUM_ASIA/HO_CHI_MINH.value = "Asia/Ho_Chi_Minh";
        ENUM_ASIA/HONG_KONG.value = "Asia/Hong_Kong";
        ENUM_ASIA/HOVD.value = "Asia/Hovd";
        ENUM_ASIA/IRKUTSK.value = "Asia/Irkutsk";
        ENUM_ASIA/JAKARTA.value = "Asia/Jakarta";
        ENUM_ASIA/JAYAPURA.value = "Asia/Jayapura";
        ENUM_ASIA/JERUSALEM.value = "Asia/Jerusalem";
        ENUM_ASIA/KABUL.value = "Asia/Kabul";
        ENUM_ASIA/KAMCHATKA.value = "Asia/Kamchatka";
        ENUM_ASIA/KARACHI.value = "Asia/Karachi";
        ENUM_ASIA/KASHGAR.value = "Asia/Kashgar";
        ENUM_ASIA/KATHMANDU.value = "Asia/Kathmandu";
        ENUM_ASIA/KHANDYGA.value = "Asia/Khandyga";
        ENUM_ASIA/KOLKATA.value = "Asia/Kolkata";
        ENUM_ASIA/KRASNOYARSK.value = "Asia/Krasnoyarsk";
        ENUM_ASIA/KUALA_LUMPUR.value = "Asia/Kuala_Lumpur";
        ENUM_ASIA/KUCHING.value = "Asia/Kuching";
        ENUM_ASIA/KUWAIT.value = "Asia/Kuwait";
        ENUM_ASIA/MACAU.value = "Asia/Macau";
        ENUM_ASIA/MAGADAN.value = "Asia/Magadan";
        ENUM_ASIA/MAKASSAR.value = "Asia/Makassar";
        ENUM_ASIA/MANILA.value = "Asia/Manila";
        ENUM_ASIA/MUSCAT.value = "Asia/Muscat";
        ENUM_ASIA/NICOSIA.value = "Asia/Nicosia";
        ENUM_ASIA/NOVOKUZNETSK.value = "Asia/Novokuznetsk";
        ENUM_ASIA/NOVOSIBIRSK.value = "Asia/Novosibirsk";
        ENUM_ASIA/OMSK.value = "Asia/Omsk";
        ENUM_ASIA/ORAL.value = "Asia/Oral";
        ENUM_ASIA/PHNOM_PENH.value = "Asia/Phnom_Penh";
        ENUM_ASIA/PONTIANAK.value = "Asia/Pontianak";
        ENUM_ASIA/PYONGYANG.value = "Asia/Pyongyang";
        ENUM_ASIA/QATAR.value = "Asia/Qatar";
        ENUM_ASIA/QYZYLORDA.value = "Asia/Qyzylorda";
        ENUM_ASIA/RANGOON.value = "Asia/Rangoon";
        ENUM_ASIA/RIYADH.value = "Asia/Riyadh";
        ENUM_ASIA/SAKHALIN.value = "Asia/Sakhalin";
        ENUM_ASIA/SAMARKAND.value = "Asia/Samarkand";
        ENUM_ASIA/SEOUL.value = "Asia/Seoul";
        ENUM_ASIA/SHANGHAI.value = "Asia/Shanghai";
        ENUM_ASIA/SINGAPORE.value = "Asia/Singapore";
        ENUM_ASIA/TAIPEI.value = "Asia/Taipei";
        ENUM_ASIA/TASHKENT.value = "Asia/Tashkent";
        ENUM_ASIA/TBILISI.value = "Asia/Tbilisi";
        ENUM_ASIA/TEHRAN.value = "Asia/Tehran";
        ENUM_ASIA/THIMPHU.value = "Asia/Thimphu";
        ENUM_ASIA/TOKYO.value = "Asia/Tokyo";
        ENUM_ASIA/ULAANBAATAR.value = "Asia/Ulaanbaatar";
        ENUM_ASIA/URUMQI.value = "Asia/Urumqi";
        ENUM_ASIA/UST-NERA.value = "Asia/Ust-Nera";
        ENUM_ASIA/VIENTIANE.value = "Asia/Vientiane";
        ENUM_ASIA/VLADIVOSTOK.value = "Asia/Vladivostok";
        ENUM_ASIA/YAKUTSK.value = "Asia/Yakutsk";
        ENUM_ASIA/YEKATERINBURG.value = "Asia/Yekaterinburg";
        ENUM_ASIA/YEREVAN.value = "Asia/Yerevan";
        ENUM_ATLANTIC/AZORES.value = "Atlantic/Azores";
        ENUM_ATLANTIC/BERMUDA.value = "Atlantic/Bermuda";
        ENUM_ATLANTIC/CANARY.value = "Atlantic/Canary";
        ENUM_ATLANTIC/CAPE_VERDE.value = "Atlantic/Cape_Verde";
        ENUM_ATLANTIC/FAROE.value = "Atlantic/Faroe";
        ENUM_ATLANTIC/MADEIRA.value = "Atlantic/Madeira";
        ENUM_ATLANTIC/REYKJAVIK.value = "Atlantic/Reykjavik";
        ENUM_ATLANTIC/SOUTH_GEORGIA.value = "Atlantic/South_Georgia";
        ENUM_ATLANTIC/ST_HELENA.value = "Atlantic/St_Helena";
        ENUM_ATLANTIC/STANLEY.value = "Atlantic/Stanley";
        ENUM_AUSTRALIA/ADELAIDE.value = "Australia/Adelaide";
        ENUM_AUSTRALIA/BRISBANE.value = "Australia/Brisbane";
        ENUM_AUSTRALIA/BROKEN_HILL.value = "Australia/Broken_Hill";
        ENUM_AUSTRALIA/CURRIE.value = "Australia/Currie";
        ENUM_AUSTRALIA/DARWIN.value = "Australia/Darwin";
        ENUM_AUSTRALIA/EUCLA.value = "Australia/Eucla";
        ENUM_AUSTRALIA/HOBART.value = "Australia/Hobart";
        ENUM_AUSTRALIA/LINDEMAN.value = "Australia/Lindeman";
        ENUM_AUSTRALIA/LORD_HOWE.value = "Australia/Lord_Howe";
        ENUM_AUSTRALIA/MELBOURNE.value = "Australia/Melbourne";
        ENUM_AUSTRALIA/PERTH.value = "Australia/Perth";
        ENUM_AUSTRALIA/SYDNEY.value = "Australia/Sydney";
        ENUM_EUROPE/AMSTERDAM.value = "Europe/Amsterdam";
        ENUM_EUROPE/ANDORRA.value = "Europe/Andorra";
        ENUM_EUROPE/ATHENS.value = "Europe/Athens";
        ENUM_EUROPE/BELGRADE.value = "Europe/Belgrade";
        ENUM_EUROPE/BERLIN.value = "Europe/Berlin";
        ENUM_EUROPE/BRATISLAVA.value = "Europe/Bratislava";
        ENUM_EUROPE/BRUSSELS.value = "Europe/Brussels";
        ENUM_EUROPE/BUCHAREST.value = "Europe/Bucharest";
        ENUM_EUROPE/BUDAPEST.value = "Europe/Budapest";
        ENUM_EUROPE/BUSINGEN.value = "Europe/Busingen";
        ENUM_EUROPE/CHISINAU.value = "Europe/Chisinau";
        ENUM_EUROPE/COPENHAGEN.value = "Europe/Copenhagen";
        ENUM_EUROPE/DUBLIN.value = "Europe/Dublin";
        ENUM_EUROPE/GIBRALTAR.value = "Europe/Gibraltar";
        ENUM_EUROPE/GUERNSEY.value = "Europe/Guernsey";
        ENUM_EUROPE/HELSINKI.value = "Europe/Helsinki";
        ENUM_EUROPE/ISLE_OF_MAN.value = "Europe/Isle_of_Man";
        ENUM_EUROPE/ISTANBUL.value = "Europe/Istanbul";
        ENUM_EUROPE/JERSEY.value = "Europe/Jersey";
        ENUM_EUROPE/KALININGRAD.value = "Europe/Kaliningrad";
        ENUM_EUROPE/KIEV.value = "Europe/Kiev";
        ENUM_EUROPE/LISBON.value = "Europe/Lisbon";
        ENUM_EUROPE/LJUBLJANA.value = "Europe/Ljubljana";
        ENUM_EUROPE/LONDON.value = "Europe/London";
        ENUM_EUROPE/LUXEMBOURG.value = "Europe/Luxembourg";
        ENUM_EUROPE/MADRID.value = "Europe/Madrid";
        ENUM_EUROPE/MALTA.value = "Europe/Malta";
        ENUM_EUROPE/MARIEHAMN.value = "Europe/Mariehamn";
        ENUM_EUROPE/MINSK.value = "Europe/Minsk";
        ENUM_EUROPE/MONACO.value = "Europe/Monaco";
        ENUM_EUROPE/MOSCOW.value = "Europe/Moscow";
        ENUM_EUROPE/OSLO.value = "Europe/Oslo";
        ENUM_EUROPE/PARIS.value = "Europe/Paris";
        ENUM_EUROPE/PODGORICA.value = "Europe/Podgorica";
        ENUM_EUROPE/PRAGUE.value = "Europe/Prague";
        ENUM_EUROPE/RIGA.value = "Europe/Riga";
        ENUM_EUROPE/ROME.value = "Europe/Rome";
        ENUM_EUROPE/SAMARA.value = "Europe/Samara";
        ENUM_EUROPE/SAN_MARINO.value = "Europe/San_Marino";
        ENUM_EUROPE/SARAJEVO.value = "Europe/Sarajevo";
        ENUM_EUROPE/SIMFEROPOL.value = "Europe/Simferopol";
        ENUM_EUROPE/SKOPJE.value = "Europe/Skopje";
        ENUM_EUROPE/SOFIA.value = "Europe/Sofia";
        ENUM_EUROPE/STOCKHOLM.value = "Europe/Stockholm";
        ENUM_EUROPE/TALLINN.value = "Europe/Tallinn";
        ENUM_EUROPE/TIRANE.value = "Europe/Tirane";
        ENUM_EUROPE/UZHGOROD.value = "Europe/Uzhgorod";
        ENUM_EUROPE/VADUZ.value = "Europe/Vaduz";
        ENUM_EUROPE/VATICAN.value = "Europe/Vatican";
        ENUM_EUROPE/VIENNA.value = "Europe/Vienna";
        ENUM_EUROPE/VILNIUS.value = "Europe/Vilnius";
        ENUM_EUROPE/VOLGOGRAD.value = "Europe/Volgograd";
        ENUM_EUROPE/WARSAW.value = "Europe/Warsaw";
        ENUM_EUROPE/ZAGREB.value = "Europe/Zagreb";
        ENUM_EUROPE/ZAPOROZHYE.value = "Europe/Zaporozhye";
        ENUM_EUROPE/ZURICH.value = "Europe/Zurich";
        GMT.value = "GMT";
        ENUM_INDIAN/ANTANANARIVO.value = "Indian/Antananarivo";
        ENUM_INDIAN/CHAGOS.value = "Indian/Chagos";
        ENUM_INDIAN/CHRISTMAS.value = "Indian/Christmas";
        ENUM_INDIAN/COCOS.value = "Indian/Cocos";
        ENUM_INDIAN/COMORO.value = "Indian/Comoro";
        ENUM_INDIAN/KERGUELEN.value = "Indian/Kerguelen";
        ENUM_INDIAN/MAHE.value = "Indian/Mahe";
        ENUM_INDIAN/MALDIVES.value = "Indian/Maldives";
        ENUM_INDIAN/MAURITIUS.value = "Indian/Mauritius";
        ENUM_INDIAN/MAYOTTE.value = "Indian/Mayotte";
        ENUM_INDIAN/REUNION.value = "Indian/Reunion";
        ENUM_PACIFIC/APIA.value = "Pacific/Apia";
        ENUM_PACIFIC/AUCKLAND.value = "Pacific/Auckland";
        ENUM_PACIFIC/CHATHAM.value = "Pacific/Chatham";
        ENUM_PACIFIC/CHUUK.value = "Pacific/Chuuk";
        ENUM_PACIFIC/EASTER.value = "Pacific/Easter";
        ENUM_PACIFIC/EFATE.value = "Pacific/Efate";
        ENUM_PACIFIC/ENDERBURY.value = "Pacific/Enderbury";
        ENUM_PACIFIC/FAKAOFO.value = "Pacific/Fakaofo";
        ENUM_PACIFIC/FIJI.value = "Pacific/Fiji";
        ENUM_PACIFIC/FUNAFUTI.value = "Pacific/Funafuti";
        ENUM_PACIFIC/GALAPAGOS.value = "Pacific/Galapagos";
        ENUM_PACIFIC/GAMBIER.value = "Pacific/Gambier";
        ENUM_PACIFIC/GUADALCANAL.value = "Pacific/Guadalcanal";
        ENUM_PACIFIC/GUAM.value = "Pacific/Guam";
        ENUM_PACIFIC/HONOLULU.value = "Pacific/Honolulu";
        ENUM_PACIFIC/JOHNSTON.value = "Pacific/Johnston";
        ENUM_PACIFIC/KIRITIMATI.value = "Pacific/Kiritimati";
        ENUM_PACIFIC/KOSRAE.value = "Pacific/Kosrae";
        ENUM_PACIFIC/KWAJALEIN.value = "Pacific/Kwajalein";
        ENUM_PACIFIC/MAJURO.value = "Pacific/Majuro";
        ENUM_PACIFIC/MARQUESAS.value = "Pacific/Marquesas";
        ENUM_PACIFIC/MIDWAY.value = "Pacific/Midway";
        ENUM_PACIFIC/NAURU.value = "Pacific/Nauru";
        ENUM_PACIFIC/NIUE.value = "Pacific/Niue";
        ENUM_PACIFIC/NORFOLK.value = "Pacific/Norfolk";
        ENUM_PACIFIC/NOUMEA.value = "Pacific/Noumea";
        ENUM_PACIFIC/PAGO_PAGO.value = "Pacific/Pago_Pago";
        ENUM_PACIFIC/PALAU.value = "Pacific/Palau";
        ENUM_PACIFIC/PITCAIRN.value = "Pacific/Pitcairn";
        ENUM_PACIFIC/POHNPEI.value = "Pacific/Pohnpei";
        ENUM_PACIFIC/PORT_MORESBY.value = "Pacific/Port_Moresby";
        ENUM_PACIFIC/RAROTONGA.value = "Pacific/Rarotonga";
        ENUM_PACIFIC/SAIPAN.value = "Pacific/Saipan";
        ENUM_PACIFIC/TAHITI.value = "Pacific/Tahiti";
        ENUM_PACIFIC/TARAWA.value = "Pacific/Tarawa";
        ENUM_PACIFIC/TONGATAPU.value = "Pacific/Tongatapu";
        ENUM_PACIFIC/WAKE.value = "Pacific/Wake";
        ENUM_PACIFIC/WALLIS.value = "Pacific/Wallis";

        valueMap.put("Africa/Abidjan", ENUM_AFRICA/ABIDJAN);
        valueMap.put("Africa/Accra", ENUM_AFRICA/ACCRA);
        valueMap.put("Africa/Addis_Ababa", ENUM_AFRICA/ADDIS_ABABA);
        valueMap.put("Africa/Algiers", ENUM_AFRICA/ALGIERS);
        valueMap.put("Africa/Asmara", ENUM_AFRICA/ASMARA);
        valueMap.put("Africa/Bamako", ENUM_AFRICA/BAMAKO);
        valueMap.put("Africa/Bangui", ENUM_AFRICA/BANGUI);
        valueMap.put("Africa/Banjul", ENUM_AFRICA/BANJUL);
        valueMap.put("Africa/Bissau", ENUM_AFRICA/BISSAU);
        valueMap.put("Africa/Blantyre", ENUM_AFRICA/BLANTYRE);
        valueMap.put("Africa/Brazzaville", ENUM_AFRICA/BRAZZAVILLE);
        valueMap.put("Africa/Bujumbura", ENUM_AFRICA/BUJUMBURA);
        valueMap.put("Africa/Cairo", ENUM_AFRICA/CAIRO);
        valueMap.put("Africa/Casablanca", ENUM_AFRICA/CASABLANCA);
        valueMap.put("Africa/Ceuta", ENUM_AFRICA/CEUTA);
        valueMap.put("Africa/Conakry", ENUM_AFRICA/CONAKRY);
        valueMap.put("Africa/Dakar", ENUM_AFRICA/DAKAR);
        valueMap.put("Africa/Dar_es_Salaam", ENUM_AFRICA/DAR_ES_SALAAM);
        valueMap.put("Africa/Djibouti", ENUM_AFRICA/DJIBOUTI);
        valueMap.put("Africa/Douala", ENUM_AFRICA/DOUALA);
        valueMap.put("Africa/El_Aaiun", ENUM_AFRICA/EL_AAIUN);
        valueMap.put("Africa/Freetown", ENUM_AFRICA/FREETOWN);
        valueMap.put("Africa/Gaborone", ENUM_AFRICA/GABORONE);
        valueMap.put("Africa/Harare", ENUM_AFRICA/HARARE);
        valueMap.put("Africa/Johannesburg", ENUM_AFRICA/JOHANNESBURG);
        valueMap.put("Africa/Juba", ENUM_AFRICA/JUBA);
        valueMap.put("Africa/Kampala", ENUM_AFRICA/KAMPALA);
        valueMap.put("Africa/Khartoum", ENUM_AFRICA/KHARTOUM);
        valueMap.put("Africa/Kigali", ENUM_AFRICA/KIGALI);
        valueMap.put("Africa/Kinshasa", ENUM_AFRICA/KINSHASA);
        valueMap.put("Africa/Lagos", ENUM_AFRICA/LAGOS);
        valueMap.put("Africa/Libreville", ENUM_AFRICA/LIBREVILLE);
        valueMap.put("Africa/Lome", ENUM_AFRICA/LOME);
        valueMap.put("Africa/Luanda", ENUM_AFRICA/LUANDA);
        valueMap.put("Africa/Lubumbashi", ENUM_AFRICA/LUBUMBASHI);
        valueMap.put("Africa/Lusaka", ENUM_AFRICA/LUSAKA);
        valueMap.put("Africa/Malabo", ENUM_AFRICA/MALABO);
        valueMap.put("Africa/Maputo", ENUM_AFRICA/MAPUTO);
        valueMap.put("Africa/Maseru", ENUM_AFRICA/MASERU);
        valueMap.put("Africa/Mbabane", ENUM_AFRICA/MBABANE);
        valueMap.put("Africa/Mogadishu", ENUM_AFRICA/MOGADISHU);
        valueMap.put("Africa/Monrovia", ENUM_AFRICA/MONROVIA);
        valueMap.put("Africa/Nairobi", ENUM_AFRICA/NAIROBI);
        valueMap.put("Africa/Ndjamena", ENUM_AFRICA/NDJAMENA);
        valueMap.put("Africa/Niamey", ENUM_AFRICA/NIAMEY);
        valueMap.put("Africa/Nouakchott", ENUM_AFRICA/NOUAKCHOTT);
        valueMap.put("Africa/Ouagadougou", ENUM_AFRICA/OUAGADOUGOU);
        valueMap.put("Africa/Porto-Novo", ENUM_AFRICA/PORTO-NOVO);
        valueMap.put("Africa/Sao_Tome", ENUM_AFRICA/SAO_TOME);
        valueMap.put("Africa/Tripoli", ENUM_AFRICA/TRIPOLI);
        valueMap.put("Africa/Tunis", ENUM_AFRICA/TUNIS);
        valueMap.put("Africa/Windhoek", ENUM_AFRICA/WINDHOEK);
        valueMap.put("America/Adak", ENUM_AMERICA/ADAK);
        valueMap.put("America/Anchorage", ENUM_AMERICA/ANCHORAGE);
        valueMap.put("America/Anguilla", ENUM_AMERICA/ANGUILLA);
        valueMap.put("America/Antigua", ENUM_AMERICA/ANTIGUA);
        valueMap.put("America/Araguaina", ENUM_AMERICA/ARAGUAINA);
        valueMap.put("America/Argentina/Buenos_Aires", ENUM_AMERICA/ARGENTINA/BUENOS_AIRES);
        valueMap.put("America/Argentina/Catamarca", ENUM_AMERICA/ARGENTINA/CATAMARCA);
        valueMap.put("America/Argentina/Cordoba", ENUM_AMERICA/ARGENTINA/CORDOBA);
        valueMap.put("America/Argentina/Jujuy", ENUM_AMERICA/ARGENTINA/JUJUY);
        valueMap.put("America/Argentina/La_Rioja", ENUM_AMERICA/ARGENTINA/LA_RIOJA);
        valueMap.put("America/Argentina/Mendoza", ENUM_AMERICA/ARGENTINA/MENDOZA);
        valueMap.put("America/Argentina/Rio_Gallegos", ENUM_AMERICA/ARGENTINA/RIO_GALLEGOS);
        valueMap.put("America/Argentina/Salta", ENUM_AMERICA/ARGENTINA/SALTA);
        valueMap.put("America/Argentina/San_Juan", ENUM_AMERICA/ARGENTINA/SAN_JUAN);
        valueMap.put("America/Argentina/San_Luis", ENUM_AMERICA/ARGENTINA/SAN_LUIS);
        valueMap.put("America/Argentina/Tucuman", ENUM_AMERICA/ARGENTINA/TUCUMAN);
        valueMap.put("America/Argentina/Ushuaia", ENUM_AMERICA/ARGENTINA/USHUAIA);
        valueMap.put("America/Aruba", ENUM_AMERICA/ARUBA);
        valueMap.put("America/Asuncion", ENUM_AMERICA/ASUNCION);
        valueMap.put("America/Atikokan", ENUM_AMERICA/ATIKOKAN);
        valueMap.put("America/Bahia", ENUM_AMERICA/BAHIA);
        valueMap.put("America/Bahia_Banderas", ENUM_AMERICA/BAHIA_BANDERAS);
        valueMap.put("America/Barbados", ENUM_AMERICA/BARBADOS);
        valueMap.put("America/Belem", ENUM_AMERICA/BELEM);
        valueMap.put("America/Belize", ENUM_AMERICA/BELIZE);
        valueMap.put("America/Blanc-Sablon", ENUM_AMERICA/BLANC-SABLON);
        valueMap.put("America/Boa_Vista", ENUM_AMERICA/BOA_VISTA);
        valueMap.put("America/Bogota", ENUM_AMERICA/BOGOTA);
        valueMap.put("America/Boise", ENUM_AMERICA/BOISE);
        valueMap.put("America/Cambridge_Bay", ENUM_AMERICA/CAMBRIDGE_BAY);
        valueMap.put("America/Campo_Grande", ENUM_AMERICA/CAMPO_GRANDE);
        valueMap.put("America/Cancun", ENUM_AMERICA/CANCUN);
        valueMap.put("America/Caracas", ENUM_AMERICA/CARACAS);
        valueMap.put("America/Cayenne", ENUM_AMERICA/CAYENNE);
        valueMap.put("America/Cayman", ENUM_AMERICA/CAYMAN);
        valueMap.put("America/Chicago", ENUM_AMERICA/CHICAGO);
        valueMap.put("America/Chihuahua", ENUM_AMERICA/CHIHUAHUA);
        valueMap.put("America/Costa_Rica", ENUM_AMERICA/COSTA_RICA);
        valueMap.put("America/Creston", ENUM_AMERICA/CRESTON);
        valueMap.put("America/Cuiaba", ENUM_AMERICA/CUIABA);
        valueMap.put("America/Curacao", ENUM_AMERICA/CURACAO);
        valueMap.put("America/Danmarkshavn", ENUM_AMERICA/DANMARKSHAVN);
        valueMap.put("America/Dawson", ENUM_AMERICA/DAWSON);
        valueMap.put("America/Dawson_Creek", ENUM_AMERICA/DAWSON_CREEK);
        valueMap.put("America/Denver", ENUM_AMERICA/DENVER);
        valueMap.put("America/Detroit", ENUM_AMERICA/DETROIT);
        valueMap.put("America/Dominica", ENUM_AMERICA/DOMINICA);
        valueMap.put("America/Edmonton", ENUM_AMERICA/EDMONTON);
        valueMap.put("America/Eirunepe", ENUM_AMERICA/EIRUNEPE);
        valueMap.put("America/El_Salvador", ENUM_AMERICA/EL_SALVADOR);
        valueMap.put("America/Fortaleza", ENUM_AMERICA/FORTALEZA);
        valueMap.put("America/Glace_Bay", ENUM_AMERICA/GLACE_BAY);
        valueMap.put("America/Godthab", ENUM_AMERICA/GODTHAB);
        valueMap.put("America/Goose_Bay", ENUM_AMERICA/GOOSE_BAY);
        valueMap.put("America/Grand_Turk", ENUM_AMERICA/GRAND_TURK);
        valueMap.put("America/Grenada", ENUM_AMERICA/GRENADA);
        valueMap.put("America/Guadeloupe", ENUM_AMERICA/GUADELOUPE);
        valueMap.put("America/Guatemala", ENUM_AMERICA/GUATEMALA);
        valueMap.put("America/Guayaquil", ENUM_AMERICA/GUAYAQUIL);
        valueMap.put("America/Guyana", ENUM_AMERICA/GUYANA);
        valueMap.put("America/Halifax", ENUM_AMERICA/HALIFAX);
        valueMap.put("America/Havana", ENUM_AMERICA/HAVANA);
        valueMap.put("America/Hermosillo", ENUM_AMERICA/HERMOSILLO);
        valueMap.put("America/Indiana/Indianapolis", ENUM_AMERICA/INDIANA/INDIANAPOLIS);
        valueMap.put("America/Indiana/Knox", ENUM_AMERICA/INDIANA/KNOX);
        valueMap.put("America/Indiana/Marengo", ENUM_AMERICA/INDIANA/MARENGO);
        valueMap.put("America/Indiana/Petersburg", ENUM_AMERICA/INDIANA/PETERSBURG);
        valueMap.put("America/Indiana/Tell_City", ENUM_AMERICA/INDIANA/TELL_CITY);
        valueMap.put("America/Indiana/Vevay", ENUM_AMERICA/INDIANA/VEVAY);
        valueMap.put("America/Indiana/Vincennes", ENUM_AMERICA/INDIANA/VINCENNES);
        valueMap.put("America/Indiana/Winamac", ENUM_AMERICA/INDIANA/WINAMAC);
        valueMap.put("America/Inuvik", ENUM_AMERICA/INUVIK);
        valueMap.put("America/Iqaluit", ENUM_AMERICA/IQALUIT);
        valueMap.put("America/Jamaica", ENUM_AMERICA/JAMAICA);
        valueMap.put("America/Juneau", ENUM_AMERICA/JUNEAU);
        valueMap.put("America/Kentucky/Louisville", ENUM_AMERICA/KENTUCKY/LOUISVILLE);
        valueMap.put("America/Kentucky/Monticello", ENUM_AMERICA/KENTUCKY/MONTICELLO);
        valueMap.put("America/Kralendijk", ENUM_AMERICA/KRALENDIJK);
        valueMap.put("America/La_Paz", ENUM_AMERICA/LA_PAZ);
        valueMap.put("America/Lima", ENUM_AMERICA/LIMA);
        valueMap.put("America/Los_Angeles", ENUM_AMERICA/LOS_ANGELES);
        valueMap.put("America/Lower_Princes", ENUM_AMERICA/LOWER_PRINCES);
        valueMap.put("America/Maceio", ENUM_AMERICA/MACEIO);
        valueMap.put("America/Managua", ENUM_AMERICA/MANAGUA);
        valueMap.put("America/Manaus", ENUM_AMERICA/MANAUS);
        valueMap.put("America/Marigot", ENUM_AMERICA/MARIGOT);
        valueMap.put("America/Martinique", ENUM_AMERICA/MARTINIQUE);
        valueMap.put("America/Matamoros", ENUM_AMERICA/MATAMOROS);
        valueMap.put("America/Mazatlan", ENUM_AMERICA/MAZATLAN);
        valueMap.put("America/Menominee", ENUM_AMERICA/MENOMINEE);
        valueMap.put("America/Merida", ENUM_AMERICA/MERIDA);
        valueMap.put("America/Metlakatla", ENUM_AMERICA/METLAKATLA);
        valueMap.put("America/Mexico_City", ENUM_AMERICA/MEXICO_CITY);
        valueMap.put("America/Miquelon", ENUM_AMERICA/MIQUELON);
        valueMap.put("America/Moncton", ENUM_AMERICA/MONCTON);
        valueMap.put("America/Monterrey", ENUM_AMERICA/MONTERREY);
        valueMap.put("America/Montevideo", ENUM_AMERICA/MONTEVIDEO);
        valueMap.put("America/Montserrat", ENUM_AMERICA/MONTSERRAT);
        valueMap.put("America/Nassau", ENUM_AMERICA/NASSAU);
        valueMap.put("America/New_York", ENUM_AMERICA/NEW_YORK);
        valueMap.put("America/Nipigon", ENUM_AMERICA/NIPIGON);
        valueMap.put("America/Nome", ENUM_AMERICA/NOME);
        valueMap.put("America/Noronha", ENUM_AMERICA/NORONHA);
        valueMap.put("America/North_Dakota/Beulah", ENUM_AMERICA/NORTH_DAKOTA/BEULAH);
        valueMap.put("America/North_Dakota/Center", ENUM_AMERICA/NORTH_DAKOTA/CENTER);
        valueMap.put("America/North_Dakota/New_Salem", ENUM_AMERICA/NORTH_DAKOTA/NEW_SALEM);
        valueMap.put("America/Ojinaga", ENUM_AMERICA/OJINAGA);
        valueMap.put("America/Panama", ENUM_AMERICA/PANAMA);
        valueMap.put("America/Pangnirtung", ENUM_AMERICA/PANGNIRTUNG);
        valueMap.put("America/Paramaribo", ENUM_AMERICA/PARAMARIBO);
        valueMap.put("America/Phoenix", ENUM_AMERICA/PHOENIX);
        valueMap.put("America/Port-au-Prince", ENUM_AMERICA/PORT-AU-PRINCE);
        valueMap.put("America/Port_of_Spain", ENUM_AMERICA/PORT_OF_SPAIN);
        valueMap.put("America/Porto_Velho", ENUM_AMERICA/PORTO_VELHO);
        valueMap.put("America/Puerto_Rico", ENUM_AMERICA/PUERTO_RICO);
        valueMap.put("America/Rainy_River", ENUM_AMERICA/RAINY_RIVER);
        valueMap.put("America/Rankin_Inlet", ENUM_AMERICA/RANKIN_INLET);
        valueMap.put("America/Recife", ENUM_AMERICA/RECIFE);
        valueMap.put("America/Regina", ENUM_AMERICA/REGINA);
        valueMap.put("America/Resolute", ENUM_AMERICA/RESOLUTE);
        valueMap.put("America/Rio_Branco", ENUM_AMERICA/RIO_BRANCO);
        valueMap.put("America/Santa_Isabel", ENUM_AMERICA/SANTA_ISABEL);
        valueMap.put("America/Santarem", ENUM_AMERICA/SANTAREM);
        valueMap.put("America/Santiago", ENUM_AMERICA/SANTIAGO);
        valueMap.put("America/Santo_Domingo", ENUM_AMERICA/SANTO_DOMINGO);
        valueMap.put("America/Sao_Paulo", ENUM_AMERICA/SAO_PAULO);
        valueMap.put("America/Scoresbysund", ENUM_AMERICA/SCORESBYSUND);
        valueMap.put("America/Sitka", ENUM_AMERICA/SITKA);
        valueMap.put("America/St_Barthelemy", ENUM_AMERICA/ST_BARTHELEMY);
        valueMap.put("America/St_Johns", ENUM_AMERICA/ST_JOHNS);
        valueMap.put("America/St_Kitts", ENUM_AMERICA/ST_KITTS);
        valueMap.put("America/St_Lucia", ENUM_AMERICA/ST_LUCIA);
        valueMap.put("America/St_Thomas", ENUM_AMERICA/ST_THOMAS);
        valueMap.put("America/St_Vincent", ENUM_AMERICA/ST_VINCENT);
        valueMap.put("America/Swift_Current", ENUM_AMERICA/SWIFT_CURRENT);
        valueMap.put("America/Tegucigalpa", ENUM_AMERICA/TEGUCIGALPA);
        valueMap.put("America/Thule", ENUM_AMERICA/THULE);
        valueMap.put("America/Thunder_Bay", ENUM_AMERICA/THUNDER_BAY);
        valueMap.put("America/Tijuana", ENUM_AMERICA/TIJUANA);
        valueMap.put("America/Toronto", ENUM_AMERICA/TORONTO);
        valueMap.put("America/Tortola", ENUM_AMERICA/TORTOLA);
        valueMap.put("America/Vancouver", ENUM_AMERICA/VANCOUVER);
        valueMap.put("America/Whitehorse", ENUM_AMERICA/WHITEHORSE);
        valueMap.put("America/Winnipeg", ENUM_AMERICA/WINNIPEG);
        valueMap.put("America/Yakutat", ENUM_AMERICA/YAKUTAT);
        valueMap.put("America/Yellowknife", ENUM_AMERICA/YELLOWKNIFE);
        valueMap.put("Antarctica/Casey", ENUM_ANTARCTICA/CASEY);
        valueMap.put("Antarctica/Davis", ENUM_ANTARCTICA/DAVIS);
        valueMap.put("Antarctica/DumontDUrville", ENUM_ANTARCTICA/DUMONTDURVILLE);
        valueMap.put("Antarctica/Macquarie", ENUM_ANTARCTICA/MACQUARIE);
        valueMap.put("Antarctica/Mawson", ENUM_ANTARCTICA/MAWSON);
        valueMap.put("Antarctica/McMurdo", ENUM_ANTARCTICA/MCMURDO);
        valueMap.put("Antarctica/Palmer", ENUM_ANTARCTICA/PALMER);
        valueMap.put("Antarctica/Rothera", ENUM_ANTARCTICA/ROTHERA);
        valueMap.put("Antarctica/Syowa", ENUM_ANTARCTICA/SYOWA);
        valueMap.put("Antarctica/Troll", ENUM_ANTARCTICA/TROLL);
        valueMap.put("Antarctica/Vostok", ENUM_ANTARCTICA/VOSTOK);
        valueMap.put("Arctic/Longyearbyen", ENUM_ARCTIC/LONGYEARBYEN);
        valueMap.put("Asia/Aden", ENUM_ASIA/ADEN);
        valueMap.put("Asia/Almaty", ENUM_ASIA/ALMATY);
        valueMap.put("Asia/Amman", ENUM_ASIA/AMMAN);
        valueMap.put("Asia/Anadyr", ENUM_ASIA/ANADYR);
        valueMap.put("Asia/Aqtau", ENUM_ASIA/AQTAU);
        valueMap.put("Asia/Aqtobe", ENUM_ASIA/AQTOBE);
        valueMap.put("Asia/Ashgabat", ENUM_ASIA/ASHGABAT);
        valueMap.put("Asia/Baghdad", ENUM_ASIA/BAGHDAD);
        valueMap.put("Asia/Bahrain", ENUM_ASIA/BAHRAIN);
        valueMap.put("Asia/Baku", ENUM_ASIA/BAKU);
        valueMap.put("Asia/Bangkok", ENUM_ASIA/BANGKOK);
        valueMap.put("Asia/Beirut", ENUM_ASIA/BEIRUT);
        valueMap.put("Asia/Bishkek", ENUM_ASIA/BISHKEK);
        valueMap.put("Asia/Brunei", ENUM_ASIA/BRUNEI);
        valueMap.put("Asia/Choibalsan", ENUM_ASIA/CHOIBALSAN);
        valueMap.put("Asia/Chongqing", ENUM_ASIA/CHONGQING);
        valueMap.put("Asia/Colombo", ENUM_ASIA/COLOMBO);
        valueMap.put("Asia/Damascus", ENUM_ASIA/DAMASCUS);
        valueMap.put("Asia/Dhaka", ENUM_ASIA/DHAKA);
        valueMap.put("Asia/Dili", ENUM_ASIA/DILI);
        valueMap.put("Asia/Dubai", ENUM_ASIA/DUBAI);
        valueMap.put("Asia/Dushanbe", ENUM_ASIA/DUSHANBE);
        valueMap.put("Asia/Gaza", ENUM_ASIA/GAZA);
        valueMap.put("Asia/Harbin", ENUM_ASIA/HARBIN);
        valueMap.put("Asia/Hebron", ENUM_ASIA/HEBRON);
        valueMap.put("Asia/Ho_Chi_Minh", ENUM_ASIA/HO_CHI_MINH);
        valueMap.put("Asia/Hong_Kong", ENUM_ASIA/HONG_KONG);
        valueMap.put("Asia/Hovd", ENUM_ASIA/HOVD);
        valueMap.put("Asia/Irkutsk", ENUM_ASIA/IRKUTSK);
        valueMap.put("Asia/Jakarta", ENUM_ASIA/JAKARTA);
        valueMap.put("Asia/Jayapura", ENUM_ASIA/JAYAPURA);
        valueMap.put("Asia/Jerusalem", ENUM_ASIA/JERUSALEM);
        valueMap.put("Asia/Kabul", ENUM_ASIA/KABUL);
        valueMap.put("Asia/Kamchatka", ENUM_ASIA/KAMCHATKA);
        valueMap.put("Asia/Karachi", ENUM_ASIA/KARACHI);
        valueMap.put("Asia/Kashgar", ENUM_ASIA/KASHGAR);
        valueMap.put("Asia/Kathmandu", ENUM_ASIA/KATHMANDU);
        valueMap.put("Asia/Khandyga", ENUM_ASIA/KHANDYGA);
        valueMap.put("Asia/Kolkata", ENUM_ASIA/KOLKATA);
        valueMap.put("Asia/Krasnoyarsk", ENUM_ASIA/KRASNOYARSK);
        valueMap.put("Asia/Kuala_Lumpur", ENUM_ASIA/KUALA_LUMPUR);
        valueMap.put("Asia/Kuching", ENUM_ASIA/KUCHING);
        valueMap.put("Asia/Kuwait", ENUM_ASIA/KUWAIT);
        valueMap.put("Asia/Macau", ENUM_ASIA/MACAU);
        valueMap.put("Asia/Magadan", ENUM_ASIA/MAGADAN);
        valueMap.put("Asia/Makassar", ENUM_ASIA/MAKASSAR);
        valueMap.put("Asia/Manila", ENUM_ASIA/MANILA);
        valueMap.put("Asia/Muscat", ENUM_ASIA/MUSCAT);
        valueMap.put("Asia/Nicosia", ENUM_ASIA/NICOSIA);
        valueMap.put("Asia/Novokuznetsk", ENUM_ASIA/NOVOKUZNETSK);
        valueMap.put("Asia/Novosibirsk", ENUM_ASIA/NOVOSIBIRSK);
        valueMap.put("Asia/Omsk", ENUM_ASIA/OMSK);
        valueMap.put("Asia/Oral", ENUM_ASIA/ORAL);
        valueMap.put("Asia/Phnom_Penh", ENUM_ASIA/PHNOM_PENH);
        valueMap.put("Asia/Pontianak", ENUM_ASIA/PONTIANAK);
        valueMap.put("Asia/Pyongyang", ENUM_ASIA/PYONGYANG);
        valueMap.put("Asia/Qatar", ENUM_ASIA/QATAR);
        valueMap.put("Asia/Qyzylorda", ENUM_ASIA/QYZYLORDA);
        valueMap.put("Asia/Rangoon", ENUM_ASIA/RANGOON);
        valueMap.put("Asia/Riyadh", ENUM_ASIA/RIYADH);
        valueMap.put("Asia/Sakhalin", ENUM_ASIA/SAKHALIN);
        valueMap.put("Asia/Samarkand", ENUM_ASIA/SAMARKAND);
        valueMap.put("Asia/Seoul", ENUM_ASIA/SEOUL);
        valueMap.put("Asia/Shanghai", ENUM_ASIA/SHANGHAI);
        valueMap.put("Asia/Singapore", ENUM_ASIA/SINGAPORE);
        valueMap.put("Asia/Taipei", ENUM_ASIA/TAIPEI);
        valueMap.put("Asia/Tashkent", ENUM_ASIA/TASHKENT);
        valueMap.put("Asia/Tbilisi", ENUM_ASIA/TBILISI);
        valueMap.put("Asia/Tehran", ENUM_ASIA/TEHRAN);
        valueMap.put("Asia/Thimphu", ENUM_ASIA/THIMPHU);
        valueMap.put("Asia/Tokyo", ENUM_ASIA/TOKYO);
        valueMap.put("Asia/Ulaanbaatar", ENUM_ASIA/ULAANBAATAR);
        valueMap.put("Asia/Urumqi", ENUM_ASIA/URUMQI);
        valueMap.put("Asia/Ust-Nera", ENUM_ASIA/UST-NERA);
        valueMap.put("Asia/Vientiane", ENUM_ASIA/VIENTIANE);
        valueMap.put("Asia/Vladivostok", ENUM_ASIA/VLADIVOSTOK);
        valueMap.put("Asia/Yakutsk", ENUM_ASIA/YAKUTSK);
        valueMap.put("Asia/Yekaterinburg", ENUM_ASIA/YEKATERINBURG);
        valueMap.put("Asia/Yerevan", ENUM_ASIA/YEREVAN);
        valueMap.put("Atlantic/Azores", ENUM_ATLANTIC/AZORES);
        valueMap.put("Atlantic/Bermuda", ENUM_ATLANTIC/BERMUDA);
        valueMap.put("Atlantic/Canary", ENUM_ATLANTIC/CANARY);
        valueMap.put("Atlantic/Cape_Verde", ENUM_ATLANTIC/CAPE_VERDE);
        valueMap.put("Atlantic/Faroe", ENUM_ATLANTIC/FAROE);
        valueMap.put("Atlantic/Madeira", ENUM_ATLANTIC/MADEIRA);
        valueMap.put("Atlantic/Reykjavik", ENUM_ATLANTIC/REYKJAVIK);
        valueMap.put("Atlantic/South_Georgia", ENUM_ATLANTIC/SOUTH_GEORGIA);
        valueMap.put("Atlantic/St_Helena", ENUM_ATLANTIC/ST_HELENA);
        valueMap.put("Atlantic/Stanley", ENUM_ATLANTIC/STANLEY);
        valueMap.put("Australia/Adelaide", ENUM_AUSTRALIA/ADELAIDE);
        valueMap.put("Australia/Brisbane", ENUM_AUSTRALIA/BRISBANE);
        valueMap.put("Australia/Broken_Hill", ENUM_AUSTRALIA/BROKEN_HILL);
        valueMap.put("Australia/Currie", ENUM_AUSTRALIA/CURRIE);
        valueMap.put("Australia/Darwin", ENUM_AUSTRALIA/DARWIN);
        valueMap.put("Australia/Eucla", ENUM_AUSTRALIA/EUCLA);
        valueMap.put("Australia/Hobart", ENUM_AUSTRALIA/HOBART);
        valueMap.put("Australia/Lindeman", ENUM_AUSTRALIA/LINDEMAN);
        valueMap.put("Australia/Lord_Howe", ENUM_AUSTRALIA/LORD_HOWE);
        valueMap.put("Australia/Melbourne", ENUM_AUSTRALIA/MELBOURNE);
        valueMap.put("Australia/Perth", ENUM_AUSTRALIA/PERTH);
        valueMap.put("Australia/Sydney", ENUM_AUSTRALIA/SYDNEY);
        valueMap.put("Europe/Amsterdam", ENUM_EUROPE/AMSTERDAM);
        valueMap.put("Europe/Andorra", ENUM_EUROPE/ANDORRA);
        valueMap.put("Europe/Athens", ENUM_EUROPE/ATHENS);
        valueMap.put("Europe/Belgrade", ENUM_EUROPE/BELGRADE);
        valueMap.put("Europe/Berlin", ENUM_EUROPE/BERLIN);
        valueMap.put("Europe/Bratislava", ENUM_EUROPE/BRATISLAVA);
        valueMap.put("Europe/Brussels", ENUM_EUROPE/BRUSSELS);
        valueMap.put("Europe/Bucharest", ENUM_EUROPE/BUCHAREST);
        valueMap.put("Europe/Budapest", ENUM_EUROPE/BUDAPEST);
        valueMap.put("Europe/Busingen", ENUM_EUROPE/BUSINGEN);
        valueMap.put("Europe/Chisinau", ENUM_EUROPE/CHISINAU);
        valueMap.put("Europe/Copenhagen", ENUM_EUROPE/COPENHAGEN);
        valueMap.put("Europe/Dublin", ENUM_EUROPE/DUBLIN);
        valueMap.put("Europe/Gibraltar", ENUM_EUROPE/GIBRALTAR);
        valueMap.put("Europe/Guernsey", ENUM_EUROPE/GUERNSEY);
        valueMap.put("Europe/Helsinki", ENUM_EUROPE/HELSINKI);
        valueMap.put("Europe/Isle_of_Man", ENUM_EUROPE/ISLE_OF_MAN);
        valueMap.put("Europe/Istanbul", ENUM_EUROPE/ISTANBUL);
        valueMap.put("Europe/Jersey", ENUM_EUROPE/JERSEY);
        valueMap.put("Europe/Kaliningrad", ENUM_EUROPE/KALININGRAD);
        valueMap.put("Europe/Kiev", ENUM_EUROPE/KIEV);
        valueMap.put("Europe/Lisbon", ENUM_EUROPE/LISBON);
        valueMap.put("Europe/Ljubljana", ENUM_EUROPE/LJUBLJANA);
        valueMap.put("Europe/London", ENUM_EUROPE/LONDON);
        valueMap.put("Europe/Luxembourg", ENUM_EUROPE/LUXEMBOURG);
        valueMap.put("Europe/Madrid", ENUM_EUROPE/MADRID);
        valueMap.put("Europe/Malta", ENUM_EUROPE/MALTA);
        valueMap.put("Europe/Mariehamn", ENUM_EUROPE/MARIEHAMN);
        valueMap.put("Europe/Minsk", ENUM_EUROPE/MINSK);
        valueMap.put("Europe/Monaco", ENUM_EUROPE/MONACO);
        valueMap.put("Europe/Moscow", ENUM_EUROPE/MOSCOW);
        valueMap.put("Europe/Oslo", ENUM_EUROPE/OSLO);
        valueMap.put("Europe/Paris", ENUM_EUROPE/PARIS);
        valueMap.put("Europe/Podgorica", ENUM_EUROPE/PODGORICA);
        valueMap.put("Europe/Prague", ENUM_EUROPE/PRAGUE);
        valueMap.put("Europe/Riga", ENUM_EUROPE/RIGA);
        valueMap.put("Europe/Rome", ENUM_EUROPE/ROME);
        valueMap.put("Europe/Samara", ENUM_EUROPE/SAMARA);
        valueMap.put("Europe/San_Marino", ENUM_EUROPE/SAN_MARINO);
        valueMap.put("Europe/Sarajevo", ENUM_EUROPE/SARAJEVO);
        valueMap.put("Europe/Simferopol", ENUM_EUROPE/SIMFEROPOL);
        valueMap.put("Europe/Skopje", ENUM_EUROPE/SKOPJE);
        valueMap.put("Europe/Sofia", ENUM_EUROPE/SOFIA);
        valueMap.put("Europe/Stockholm", ENUM_EUROPE/STOCKHOLM);
        valueMap.put("Europe/Tallinn", ENUM_EUROPE/TALLINN);
        valueMap.put("Europe/Tirane", ENUM_EUROPE/TIRANE);
        valueMap.put("Europe/Uzhgorod", ENUM_EUROPE/UZHGOROD);
        valueMap.put("Europe/Vaduz", ENUM_EUROPE/VADUZ);
        valueMap.put("Europe/Vatican", ENUM_EUROPE/VATICAN);
        valueMap.put("Europe/Vienna", ENUM_EUROPE/VIENNA);
        valueMap.put("Europe/Vilnius", ENUM_EUROPE/VILNIUS);
        valueMap.put("Europe/Volgograd", ENUM_EUROPE/VOLGOGRAD);
        valueMap.put("Europe/Warsaw", ENUM_EUROPE/WARSAW);
        valueMap.put("Europe/Zagreb", ENUM_EUROPE/ZAGREB);
        valueMap.put("Europe/Zaporozhye", ENUM_EUROPE/ZAPOROZHYE);
        valueMap.put("Europe/Zurich", ENUM_EUROPE/ZURICH);
        valueMap.put("GMT", GMT);
        valueMap.put("Indian/Antananarivo", ENUM_INDIAN/ANTANANARIVO);
        valueMap.put("Indian/Chagos", ENUM_INDIAN/CHAGOS);
        valueMap.put("Indian/Christmas", ENUM_INDIAN/CHRISTMAS);
        valueMap.put("Indian/Cocos", ENUM_INDIAN/COCOS);
        valueMap.put("Indian/Comoro", ENUM_INDIAN/COMORO);
        valueMap.put("Indian/Kerguelen", ENUM_INDIAN/KERGUELEN);
        valueMap.put("Indian/Mahe", ENUM_INDIAN/MAHE);
        valueMap.put("Indian/Maldives", ENUM_INDIAN/MALDIVES);
        valueMap.put("Indian/Mauritius", ENUM_INDIAN/MAURITIUS);
        valueMap.put("Indian/Mayotte", ENUM_INDIAN/MAYOTTE);
        valueMap.put("Indian/Reunion", ENUM_INDIAN/REUNION);
        valueMap.put("Pacific/Apia", ENUM_PACIFIC/APIA);
        valueMap.put("Pacific/Auckland", ENUM_PACIFIC/AUCKLAND);
        valueMap.put("Pacific/Chatham", ENUM_PACIFIC/CHATHAM);
        valueMap.put("Pacific/Chuuk", ENUM_PACIFIC/CHUUK);
        valueMap.put("Pacific/Easter", ENUM_PACIFIC/EASTER);
        valueMap.put("Pacific/Efate", ENUM_PACIFIC/EFATE);
        valueMap.put("Pacific/Enderbury", ENUM_PACIFIC/ENDERBURY);
        valueMap.put("Pacific/Fakaofo", ENUM_PACIFIC/FAKAOFO);
        valueMap.put("Pacific/Fiji", ENUM_PACIFIC/FIJI);
        valueMap.put("Pacific/Funafuti", ENUM_PACIFIC/FUNAFUTI);
        valueMap.put("Pacific/Galapagos", ENUM_PACIFIC/GALAPAGOS);
        valueMap.put("Pacific/Gambier", ENUM_PACIFIC/GAMBIER);
        valueMap.put("Pacific/Guadalcanal", ENUM_PACIFIC/GUADALCANAL);
        valueMap.put("Pacific/Guam", ENUM_PACIFIC/GUAM);
        valueMap.put("Pacific/Honolulu", ENUM_PACIFIC/HONOLULU);
        valueMap.put("Pacific/Johnston", ENUM_PACIFIC/JOHNSTON);
        valueMap.put("Pacific/Kiritimati", ENUM_PACIFIC/KIRITIMATI);
        valueMap.put("Pacific/Kosrae", ENUM_PACIFIC/KOSRAE);
        valueMap.put("Pacific/Kwajalein", ENUM_PACIFIC/KWAJALEIN);
        valueMap.put("Pacific/Majuro", ENUM_PACIFIC/MAJURO);
        valueMap.put("Pacific/Marquesas", ENUM_PACIFIC/MARQUESAS);
        valueMap.put("Pacific/Midway", ENUM_PACIFIC/MIDWAY);
        valueMap.put("Pacific/Nauru", ENUM_PACIFIC/NAURU);
        valueMap.put("Pacific/Niue", ENUM_PACIFIC/NIUE);
        valueMap.put("Pacific/Norfolk", ENUM_PACIFIC/NORFOLK);
        valueMap.put("Pacific/Noumea", ENUM_PACIFIC/NOUMEA);
        valueMap.put("Pacific/Pago_Pago", ENUM_PACIFIC/PAGO_PAGO);
        valueMap.put("Pacific/Palau", ENUM_PACIFIC/PALAU);
        valueMap.put("Pacific/Pitcairn", ENUM_PACIFIC/PITCAIRN);
        valueMap.put("Pacific/Pohnpei", ENUM_PACIFIC/POHNPEI);
        valueMap.put("Pacific/Port_Moresby", ENUM_PACIFIC/PORT_MORESBY);
        valueMap.put("Pacific/Rarotonga", ENUM_PACIFIC/RAROTONGA);
        valueMap.put("Pacific/Saipan", ENUM_PACIFIC/SAIPAN);
        valueMap.put("Pacific/Tahiti", ENUM_PACIFIC/TAHITI);
        valueMap.put("Pacific/Tarawa", ENUM_PACIFIC/TARAWA);
        valueMap.put("Pacific/Tongatapu", ENUM_PACIFIC/TONGATAPU);
        valueMap.put("Pacific/Wake", ENUM_PACIFIC/WAKE);
        valueMap.put("Pacific/Wallis", ENUM_PACIFIC/WALLIS);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TimezoneEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TimezoneEnum values to list of string values
     * @param toConvert The list of TimezoneEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<TimezoneEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (TimezoneEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 