/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://example.com/api";

}
