/*
 * SVSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
package com.gotransverse.svs.webhook.client;

import com.gotransverse.svs.webhook.client.controllers.*;
import com.gotransverse.svs.webhook.client.http.client.HttpClient;

public class SVSClient {
    /**
     * Singleton access to RegisterManagement controller
     * @return	Returns the RegisterManagementController instance 
     */
    public RegisterManagementController getRegisterManagement() {
        return RegisterManagementController.getInstance();
    }

    /**
     * Singleton access to DataExport controller
     * @return	Returns the DataExportController instance 
     */
    public DataExportController getDataExport() {
        return DataExportController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public SVSClient() {	
	}

}